### ISSUE TITLE
Commit #8171483 makes it impossible to use text selection in the urlbar

### ISSUE THREAD

**Issue by mnxn** [muckSponge/MaterialFox#10]
Commit 8171483 removes the ability to highlight the text in the urlbar. The issue is also mentioned on the [reddit thread](https://www.reddit.com/r/FirefoxCSS/comments/9bh3ik/materialfox/e596gg7/).

Default Firefox:
![2018-09-02_14-16-59](https://user-images.githubusercontent.com/25037249/44960842-7b90ba80-aebb-11e8-9419-c3c5c05d5beb.gif)

MaterialFox:Master:
![2018-09-02_14-15-23](https://user-images.githubusercontent.com/25037249/44960843-7cc1e780-aebb-11e8-8e54-8bf297374e81.gif)

The mouse is being held down when dragged in both examples.

The problem stems from the `#urlbar[focused]::after` styles as it doesn't let the pointer pass through correctly. 

I have found two possible fixes:

1. Add `pointer-events: none;` to `#urlbar[focused]::after` 
__Upside__: Better than no text selections at all. 
__Downside__: urlbar must be pressed at least once before being able to select text on the second time. All text is not highlighted when you click on it for the first time. More clunkier than default Firefox.
I wouldn't use this unless fix 2 is incompatible for some reason.
![2018-09-02_14-52-07](https://user-images.githubusercontent.com/25037249/44961089-f22fb700-aebf-11e8-82e8-185f526d1476.gif)

2. Remove the entire `#urlbar[focused]::after` selector and styles, add the following style to `#urlbar[focused]` 
__Upside__: Behaves exactly like default firefox 
__Downside__: There are some artifacts on the curved parts of the outline due to `box-shadow`. Not sure if it works on MacOS correctly, I'm trying to get a VM running. 
![2018-09-02_14-50-16](https://user-images.githubusercontent.com/25037249/44961080-ad0b8500-aebf-11e8-9840-115df44204e3.gif)
```
box-shadow: 0 0 0 1px var(--textbox-outer-color-focused), 
            0 0 0 1px var(--textbox-outer-color-focused) inset !important;
````

Previous commits had a variant of the box-shadow solution, but with 2px instead, I'm not sure why it was changed to add a specific element for the border as it breaks the interactivity with the urlbar.

If you'd like to merge the second solution, my fork already has it and you can pull request from it: https://github.com/mnxn/MaterialFox

GIFs and solutions were tested on Windows 1803 with Firefox Developer Edition 63.0b2. I'll update this Issue if I find any problems with the second solution in a MacOS VM.

__Edit:__ Just checked in MacOS and it seems to work fine.

**Comment by muckSponge** [comment]
Oops! I used ```::after``` instead of the ```box-shadow``` solution to remove those corner artefacts. Didn't think about the fact that it could interrupt text selection behaviour. I'll have a play around with it today, might be easier and cleaner to apply the ```::after``` CSS to urlbar-container instead. Ideal solution should be artefact free but we obviously don't want urlbar behaviour to be affected.

**Comment by muckSponge** [comment]
Found a way to do this without the artefacts and without a pseudo element, thanks to Mozilla's ```-moz-outline-radius``` property. Could you confirm that f051620 resolves the issue? Only tested on macOS but can't see why it wouldn't work for Windows too.

**Comment by mnxn** [comment]
Works correctly with no artifacts on Windows. Great solution.

**Comment by muckSponge** [comment]
Fantastic, thanks for your help on this one! Sometimes I focus so much on how the UI looks, I don't realise when I completely break behaviour hehe.
