### ISSUE TITLE
Avatar icon overrides avatar image

### ISSUE THREAD

**Issue by locness3** [muckSponge/MaterialFox#101]
Firefox 67.0 adds a built-in profile button, with all sync things, so you should use the normal synced tabs icon for the synced tabs button instead of the "avatar" icon.

**Comment by locness3** [comment]
Sorry, didn't update my version. I see you added it. But why showing a general avatar icon, why not showing the account avatar ?

**Comment by muckSponge** [comment]
To be honest, I didn't even know you could have your own avatar image. This should be fixed now.
