### ISSUE TITLE
Auto-complete popup broken in fx 68+

### ISSUE THREAD

**Issue by kulocora** [muckSponge/MaterialFox#103]
Works fine in 67 (stable) but broken in 68+ (beta/nightly)
Tested on Windows 10 1809

![图片](https://user-images.githubusercontent.com/12947678/58384176-5b88c480-8011-11e9-83cd-fb8ff0cd5b00.png)

**Comment by muckSponge** [comment]
Work on this will be in the [popup-refresh](https://github.com/muckSponge/MaterialFox/tree/popup-refresh) branch. Be warned - it's currently even more broken in that branch but I'm aware of this and will be working on it in the coming days.

**Comment by muckSponge** [comment]
Should look pretty decent now.
