### ISSUE TITLE
Fix search box (popup-refresh branch)

### ISSUE THREAD

**Issue by locness3** [muckSponge/MaterialFox#104]
Search box, on popup-refrsh barnch looks like this :

![Capture d’écran 2019-05-27 à 18 59 51](https://user-images.githubusercontent.com/37651007/58432327-0781ec80-80b2-11e9-986e-33924fbc5e95.png)

**Comment by muckSponge** [comment]
How does it look after 39aa04344e7864afed60bd217dac42023963767b?

There's a good chance it's only going to be compatible with 68+ due to significant changes to the DOM between 67 and 68 but I haven't had a chance to test on 67 yet.

**Comment by locness3** [comment]
Looks great, but there isn't the "Search with" footer.

**Comment by muckSponge** [comment]
"Search with" footer is present for me on macOS Firefox 68 and 69. What are you running?

**Comment by locness3** [comment]
> "Search with" footer is present for me on macOS Firefox 68 and 69 (67 needs a lot of work). What are you running?

67

**Comment by muckSponge** [comment]
Should be all fixed up in 67, 68, 69. Will close; any further problems will be more specific and can have their own issue.
