### ISSUE TITLE
Missing toolkit.legacyUserProfileCustomizations.stylesheets

### ISSUE THREAD

**Issue by superjax** [muckSponge/MaterialFox#105]
Maybe I'm just missing something obvious (sorry if that's the case), but I'm wondering if this setting got changed, it is not present in my version of Firefox.

Could it be that this option has been moved?

My steps:
 1. navigate to `about:config`
 2. type `toolkit.legacyUserProfileCustomizations.stylesheets` into the search bar

Result:
 Nothing is shown.  (I also tried manually searching, and there is nothing in `toolkit.legacy*`)

Firefox Version: 67 (64-bit)
OS: Ubuntu 18.04

Thank you! I have loved using this on all my other machines. For some reason, it's not working on this fresh install.

**Comment by muckSponge** [comment]
That pref might only be available on Firefox 69 and later. Mozilla will be hiding userChrome tweaks behind that pref in this and later versions so we've added the pref to the instructions to future-proof it. If you don't see the pref, that's ok - it should work without it in 67. If it's not working, make sure your chrome folder is in your profile folder and the SVG pref is set to true. Is it not working at all?

**Comment by muckSponge** [comment]
Modified README to reflect that this is a 69+ only step.

**Comment by superjax** [comment]
Thank you!  You're correct, I had put the folder in the wrong place and was looking at that configuration as debug.
