### ISSUE TITLE
Permissions popups bug (popup-refresh branch)

### ISSUE THREAD

**Issue by locness3** [muckSponge/MaterialFox#106]
![Capture d’écran 2019-05-30 à 18 00 52](https://user-images.githubusercontent.com/37651007/58646104-00065180-8305-11e9-9158-046334b39191.png)
On `popup-refresh` branch.

**Comment by muckSponge** [comment]
Should be fixed now. Made a few selectors more generalised so hopefully this doesn't cause any regressions in lesser-used parts of the UI.

**Comment by locness3** [comment]
![Capture d’écran 2019-05-31 à 10 01 26](https://user-images.githubusercontent.com/37651007/58691009-279ffd00-838b-11e9-8fd5-4e8faa60572f.png)
Seems OK.

**Comment by muckSponge** [comment]
Thanks for testing amigo.
