### ISSUE TITLE
Context menu cut-off

### ISSUE THREAD

**Issue by ashtonlance** [muckSponge/MaterialFox#109]
Using latest macOs and Firefox 67.0.1 with MaterialFox v0.2.3

Screen shot attached.
![Screen Shot 2019-06-04 at 9 31 35 AM](https://user-images.githubusercontent.com/13652692/58883093-b7a3b680-86ab-11e9-812c-c430cfe333a9.png)

**Comment by muckSponge** [comment]
Try v0.2.4 - should be fixed now; was applying a workaround for a Windows-only issue. I've isolated the code so now it only runs on Windows.

**Comment by ashtonlance** [comment]
Dang that was fast! It's much better now.

**Comment by muckSponge** [comment]
You caught me just before I went to bed - figured I'd better fix this embarrassment beforehand ;)
