### ISSUE TITLE
Must use Light theme.

### ISSUE THREAD

**Issue by TwisterMc** [muckSponge/MaterialFox#11]
It'd be good to note in the ReadMe that Firefox should be running the Light theme in order to match the preview. Using the Default theme produces unexpected results. Using the Dark theme however, it still looks amazing.

I also want too say this is fantastic! Thank you.

**Comment by muckSponge** [comment]
That's a good suggestion! I'm in the middle of a big overhaul which should improve compatibility with default/light/dark themes (and hopefully any other themes too). Most of the code base is being changed in some way so it might take a few more days. Thanks for the kind words :)

**Comment by muckSponge** [comment]
Resolved in 1ab209982a245ef8dca4bd7a2e15261c18daacf9.
