### ISSUE TITLE
Window corners on mac

### ISSUE THREAD

**Issue by kolddoo** [muckSponge/MaterialFox#110]
Window corners don't seem to be right, as if they were not transparent.

![Screenshot](https://user-images.githubusercontent.com/51378021/58897135-88169d80-86ef-11e9-814a-c46b958e9bbc.jpg)

**Comment by muckSponge** [comment]
That's strange; can't say I've ever experienced that and I'm testing on macOS almost daily. I've checked 67 and 69 and can't reproduce the problem. Could you tell me a bit more about your setup? Firefox version, lightweight theme used (if any), customisation settings, etc.

**Comment by kolddoo** [comment]
Yes, it's very strange... I'm getting it on the two macs that I use. My settings are:

- Firefox 67.0.1
- MaterialFox 0.2.4
- Cusomization settings: drag space on, default theme (it happens with light theme too), normal density

If I remove MaterialFox and come back to the default firefox settings, window corners are fine again.

**Comment by kolddoo** [comment]
I found where the issue is. I manually enabled the gfx.webrender.all value to get webrender, if turned off to default value it is fine again. Thank you!

**Comment by muckSponge** [comment]
Just tested that setting and it also messes up the vanilla theme. Hopefully when they fix that, it will work fine with MaterialFox as well.
