### ISSUE TITLE
Move page actions menu button to the left of the bookmark icon

### ISSUE THREAD

**Issue by BynariStar** [muckSponge/MaterialFox#113]
When you hover over the address bar, the bookmark icon is often moved by an appearing page actions button. I suggest moving it to the left of the bookmark icon.

Current:
![image](https://user-images.githubusercontent.com/1224547/58902902-cbcbd000-870c-11e9-8045-61b4cf8bf54e.png)

Proposed:
![image](https://user-images.githubusercontent.com/1224547/58903240-8d82e080-870d-11e9-9572-3a8f90fe2004.png)

**Comment by muckSponge** [comment]
This should have been fixed in v0.2.0. Can you confirm you're on the latest version?

**Comment by BynariStar** [comment]
You're right, my mistake, I downloaded the repo one day before you made the change.

On a related note, I'd recommend adding a version file within the chrome folder or a line in userChrome.css to easily check what version you're on. 😃
