### ISSUE TITLE
URL Bar Bug

### ISSUE THREAD

**Issue by SalGnt** [muckSponge/MaterialFox#12]
Using the URL bar I noticed a glitch. It seems that there is something left with the default `border-radius`.

![immagine](https://user-images.githubusercontent.com/884093/45090536-e5a19d80-b10f-11e8-938e-2951bf22fc57.png)

![immagine](https://user-images.githubusercontent.com/884093/45090553-f0f4c900-b10f-11e8-8188-c9d259ac3583.png)

**Comment by muckSponge** [comment]
That's odd. I can't replicate this behaviour on Windows or macOS. What OS are you running? Do you have any add-ons or light weight themes installed?

**Comment by Esse321** [comment]
I encountered the same behavior yesterday, I will try to replicate it.

**Comment by SalGnt** [comment]
I'm on Windows 10 using the light default theme. Here are the steps to replicate it:

1. Click on the URL bar (text must be selected);
2. Hover one of the icon on the right/left of the bar (e.g. the star icon) with the mouse.

**Comment by muckSponge** [comment]
Thanks, I have replicated the issue and it appears to be some kind of bug with Firefox's ```-moz-outline-radius``` property. The urlbar focus outline isn't playing nicely with the urlbar icon ```background-color```s.

I might have to find an alternative urlbar focus outline technique.

**Comment by muckSponge** [comment]
Resolved in 1ab209982a245ef8dca4bd7a2e15261c18daacf9.
