### ISSUE TITLE
search bar is broken

### ISSUE THREAD

**Issue by TowelBin** [muckSponge/MaterialFox#120]
with the new popup styling, the search icon on the left does not show up unless you are already on a website if you are in the light theme.
![search2](https://user-images.githubusercontent.com/43922012/59675064-0412ea00-91b4-11e9-9cf3-1a40231a261a.png)
also, if you have the search 1-offs disabled there is no border radius on the bottom.
![search1](https://user-images.githubusercontent.com/43922012/59675230-5fdd7300-91b4-11e9-84f8-80f326c81de1.png)
(note that these screenshots were taken in ffx66 but this still aplies in 67)

**Comment by muckSponge** [comment]
The first issue is probably `color`-related. Second issue is something I might be able to fix with some `:last-child` selectors but failing that, I might be able to check the `browser.urlbar.oneOffSearches` pref via `@supports -moz-bool-pref("browser.urlbar.oneOffSearches")`. Won't be able to work on this until a bit later so this comment is more of a note to future self.

**Comment by muckSponge** [comment]
I'm unable to replicate either issue on macOS and Windows. There seems to be no way to remove the search one-offs footer using about:config. It will remove all the one-off buttons but the footer remains.

<img width="443" alt="image" src="https://user-images.githubusercontent.com/5405629/62697952-4243c180-ba1f-11e9-8bc5-f6e4e7a77233.png">

The incorrect urlbar styling is a separate issue on Nightly right now so ignore that.

The missing icon issue doesn't seem to be present either. I'm testing 68 and 70 so perhaps this bug resolved itself in 68 and at the same time, Mozilla introduced a regression causing the one-offs footer to remain visible despite `browser.urlbar.oneOffSearches` being `false`?

**Comment by muckSponge** [comment]
I'm going to close this due to inactivity but happy to open it again if the problem is still present in 68+.

**Comment by TowelBin** [comment]
problem is still present in 68 @muckSponge

**Comment by toby3d** [comment]
![image](https://user-images.githubusercontent.com/5412322/64320390-dc276b80-cfd7-11e9-980e-bc0b7e4a5cba.png)
v69.0b12

**Comment by muckSponge** [comment]
> ![image](https://user-images.githubusercontent.com/5412322/64320390-dc276b80-cfd7-11e9-980e-bc0b7e4a5cba.png)
> v69.0b12

This issue is actually for the urlbar search dropdown. The searchbar dropdown should go in a separate issue if you don't mind creating a new one. Unfortunately there's not much I can do to fix it at this stage in v72 due to a Firefox bug (I can't touch the elements needed to style it correctly) so I'm reluctant to fix it just for v70 (and maybe 71? Haven't tested).
