### ISSUE TITLE
padding on menu (firefox on archlinux)

### ISSUE THREAD

**Issue by edoz90** [muckSponge/MaterialFox#121]
![ma](https://user-images.githubusercontent.com/6991986/59717526-761d1a80-9218-11e9-8bd3-63ac22984f84.png)

**Comment by ChiDal** [comment]
Fine on manjaro
[https://i.imgur.com/ajWhV05.png](url)

**Comment by edoz90** [comment]
With the new update of Firefox it seems that the issue is gone.....
I'll wait 2 days and if the issue is really gone I'll close this issue
