### ISSUE TITLE
Panel buttons missing right padding (Linux)

### ISSUE THREAD

**Issue by ChiDal** [muckSponge/MaterialFox#123]
![Screenshot from 2019-06-19 18-40-02](https://user-images.githubusercontent.com/36493671/59866000-1f464b00-93a8-11e9-913f-de24644e6651.png)
This dialog is cut off 
manjaro gnome, Firefox 67.0.3

**Comment by muckSponge** [comment]
Looks fine on macOS. Haven't tested on Windows yet (been super busy the last few weeks). Probably just needs the right padding to be enforced. You'll probably see the same issue on any popups with buttons in them. Hopefully I'll have some time soon to work on this.

**Comment by muckSponge** [comment]
Looks like that commit fixed it so I'm going to close this but let me know if any other panel buttons seem to be acting up.
