### ISSUE TITLE
Material Dark theme

### ISSUE THREAD

**Issue by Excigma** [muckSponge/MaterialFox#129]
Material Dark theme:
![image](https://user-images.githubusercontent.com/30280397/61182199-0289f400-a684-11e9-9bef-8caac90e5eb2.png)

"Applies the same color palette as the incognito Google Chrome theme, making it a perfect accompaniment to MaterialFox."

Just searched around and saw: https://github.com/muckSponge/MaterialFox/issues/45#issuecomment-457799195 , meaning this theme is not needed anymore?

Should remove "accompaniment to MaterialFox" maybe?

Posting issue here as "Support site" links to here

**Comment by muckSponge** [comment]
It's no longer necessary so I'd advise disabling it, but it probably won't cause any harm having it enabled.

**Comment by Excigma** [comment]
Yeah, I made a theme using Firefox color, very nice tool!

I suggest to change the description of the theme as to not confuse people, but dude, nice work!
