### ISSUE TITLE
Customize Firefox: Some dropdowns broken

### ISSUE THREAD

**Issue by Excigma** [muckSponge/MaterialFox#130]
![image](https://user-images.githubusercontent.com/30280397/61182235-89d76780-a684-11e9-9f08-ea0a66956348.png)

![image](https://user-images.githubusercontent.com/30280397/61182244-a7a4cc80-a684-11e9-8818-1a60b8179b9a.png)

**Comment by muckSponge** [comment]
Should look much better now, let me know how it goes.

**Comment by Excigma** [comment]
Much better :)

![image](https://user-images.githubusercontent.com/30280397/62594794-ef3f1100-b92f-11e9-8f65-6bd96fc9320d.png)

![2pYsg3Zh7b](https://user-images.githubusercontent.com/30280397/62594816-0da50c80-b930-11e9-8468-710180cae1d5.gif)

**Comment by muckSponge** [comment]
Oops, forgot to fix the density menu. Everything should be in order now. I reduced the themes icon size from 32px to 24px for consistency.
