### ISSUE TITLE
Small white bar at top

### ISSUE THREAD

**Issue by privacyguy123** [muckSponge/MaterialFox#132]
Trying to remember the fix to this after updating my FireFox and not backing up my userchrome file ... in compact mode there's a small white bar appearing under the open tabs - I originally found the fix somwhere on Reddit but can't remember what to change now. :/

**Comment by muckSponge** [comment]
I can't seem to replicate this so it would be handy to see a screenshot and what OS and Firefox version you're using.

**Comment by stevebaines** [comment]
Hi, I have this too, unfortunately.  Win7 on FF 68.01 ESR
![Capture](https://user-images.githubusercontent.com/48802716/62311669-39357c00-b484-11e9-9db7-c8dd42665f0f.PNG)

**Comment by dipiana** [comment]
I have the same issue, any idea on how to fix that?

**Comment by muckSponge** [comment]
> Hi, I have this too, unfortunately. Win7 on FF 68.01 ESR
> ![Capture](https://user-images.githubusercontent.com/48802716/62311669-39357c00-b484-11e9-9db7-c8dd42665f0f.PNG)

That looks like a different issue. Grab the latest release and it should be fixed. Completely changed how I do the rounded tab shape so this shouldn't be possible any more.

As for the small white bar, haven't been able to replicate it yet but I'm almost always developing on macOS. I searched Reddit but couldn't find any reference to it.

**Comment by muckSponge** [comment]
I'm going to close this due to inactivity. If someone can replicate this issue just comment and I'll reopen.

**Comment by dipiana** [comment]
Update to the latest version worked for me - thanks.

**Comment by stevebaines** [comment]
And me. Cheers
