### ISSUE TITLE
Active tab broken on FF 68.0 and 68.0.1

### ISSUE THREAD

**Issue by s1h4d0w** [muckSponge/MaterialFox#133]
So I just got home from a 4 day vacation and noticed that my PC had rebooted, probably because of a Windows update. Now my active tab displays like this:

![image](https://user-images.githubusercontent.com/5654654/61556059-2329c380-aa61-11e9-9dd2-fe81b3040c6d.png)

I was on Firefox 68.0 (64bit) then, but when I checked it asked me to restart FF to apply an update. Thought it couldn't hurt and maybe restarting FF would fix it, but on 68.0.1 it's still broken. Not that I expected it to be fixed, I'm assuming something changed in FF 68.

All non-active tabs display just fine.

**Comment by muckSponge** [comment]
Are you sure you're on the latest version? This has been fixed for a while now and the code that used to cause this should be long gone.

**Comment by wschella** [comment]
Can confirm updating to the latest version fixed this for me.

**Comment by s1h4d0w** [comment]
You are absolutely right, but it's weird that this just happened randomly. I thought I had the latest version but after downloading and overwriting the files in my chrome folder, then restarting Firefox everything was back to normal.

Sorry!
