### ISSUE TITLE
Commit #6d95b27 breaks Firefox Account row in popup menu (Windows)

### ISSUE THREAD

**Issue by fortym2** [muckSponge/MaterialFox#136]
Hi, 

In Firefox 68.0.1 on Windows 10, the account button looks in this way:

![bug](https://user-images.githubusercontent.com/30431538/62626064-ccf4c580-b926-11e9-9672-6a2f8ad787f2.png)

This happens after commit 6d95b27b194c9189fe72140d4890efff761eb35f

**Comment by muckSponge** [comment]
That's what I get for only testing Nightly... they changed the DOM. I've updated it so it's compatible with both now.

**Comment by fortym2** [comment]
I confirm that it now works beautifully! ✔️
Thank you :)

**Comment by muckSponge** [comment]
Great, thanks for the quick bug report!
