### ISSUE TITLE
Removing EV SSL label from address bar

### ISSUE THREAD

**Issue by Madis0** [muckSponge/MaterialFox#137]
Chrome 77 is [removing the extended verification label from the address bar](https://groups.google.com/a/chromium.org/forum/m/#!msg/security-dev/h1bTcoTpfeI/jUTk1z7VAAAJ) and moving it to page info.

Since Firefox has shown the name in the page info popup for a long time (even on mobile!), I think MaterialFox should follow suit and also hide the label from the address bar. It is also useful to note that Firefox's page info [will look fairly similar to Chrome's in v70](https://mozilla.invisionapp.com/m/share/38S2U6FPFKD#/359913354).

Alternatively, you may want to add a preference (default-enabled?) to toggle this behaviour, similar to #31.

**Comment by muckSponge** [comment]
Yeah, I think this is a good idea, will see what I can do in the coming days.

**Comment by Madis0** [comment]
[Apparently Firefox plans to do it by itself](https://groups.google.com/forum/?fromgroups=&hl=en#!topic/firefox-dev/6wAg_PpnlY4) :)
