### ISSUE TITLE
urlbar oddities in 70.0a1 (2019-08-14) (64-bit)

### ISSUE THREAD

**Issue by Gigobitto** [muckSponge/MaterialFox#138]
I'd also like to be able to completely hide the one-click search engines; I used to be able to by unselecting all of them from Options -> Search, but it doesn't seem to work anymore
![image](https://user-images.githubusercontent.com/23615575/63086178-8f5bf200-bf4f-11e9-8a79-f0af1563e0ef.png)

**Comment by TowelBin** [comment]
try this:
`.search-one-offs
{
	display: block !important;
}`

**Comment by Gigobitto** [comment]
still there
![image](https://user-images.githubusercontent.com/23615575/63215492-7b6ae880-c127-11e9-9649-11f0c80cb26e.png)

**Comment by TowelBin** [comment]
try this:
`.search-one-offs { display: none !important; }`
and
`.search-panel-one-offs
{
	border-radius: 0 0 8px 8px !important;
	margin-bottom: 18px !important;
	display: none !important;
}`

**Comment by Gigobitto** [comment]
Updated, settings icon didn't change. Applied these two userChrome fixes, and those removed the annoying one-offs, ty

**Comment by TowelBin** [comment]
no problem! can you close the issue now?

**Comment by locness3** [comment]
But does the url bar dropdopdown looks betetr ?
