### ISSUE TITLE
Unnecessary navbar.css in icons folder

### ISSUE THREAD

**Issue by TowelBin** [muckSponge/MaterialFox#141]
There is an navbar.css file in the icons folder that as far as I can tell, isn't used anywhere. it is different from the actual navbar file.

**Comment by muckSponge** [comment]
I think it's an old duplicate which somehow made its way in there. Looks like it's about 2 months old. I added it around when I was moving icon code around - must have copied it temporarily while I relocated the icon code and forgot to delete it.
