### ISSUE TITLE
Buttons are black on black and have dots

### ISSUE THREAD

**Issue by ChiDal** [muckSponge/MaterialFox#142]
Firefox 68.0.2
GNOME 3.32.2 on X11

I just reinstalled arch today and have this issue.
It wasn't there on my previous install. I don't know which version of firefox i was using then.

![Screenshot from 2019-08-18 12-38-13](https://user-images.githubusercontent.com/36493671/63221349-72285d00-c1b5-11e9-9099-b22f54c92d1c.png)

For example, the new tab button is only visible when i hover over it
![Screenshot from 2019-08-18 12-38-13](https://user-images.githubusercontent.com/36493671/63221370-b156ae00-c1b5-11e9-8c12-4535becda036.png)

**Comment by muckSponge** [comment]
My spongey senses are telling me you may have missed an about:config step (search "SVG" in the readme) ;)

**Comment by ChiDal** [comment]
That was it, thanks!
