### ISSUE TITLE
home background

### ISSUE THREAD

**Issue by Rokre** [muckSponge/MaterialFox#145]
It is posible to edit the about:home and new tab backgrounds?

![Screenshot_20190821_080827](https://user-images.githubusercontent.com/41651420/63430618-00d1ef80-c3eb-11e9-9beb-dfe2e89e2489.png)

I want them to match my top bar

**Comment by TowelBin** [comment]
ask on reddit and come back once you find if it is possible/how to do it

**Comment by Excigma** [comment]
It is possible, you need a userContent.css and add 
```css
body {
   background: url("IMAGE URL HERE")
}
```

**Comment by Rokre** [comment]
thank you!!!
