### ISSUE TITLE
Firefox 70 Tracking Protection

### ISSUE THREAD

**Issue by Madis0** [muckSponge/MaterialFox#147]
Firefox 70 (currently in Nightly) is adding a [separate Tracking Protection panel](https://mozilla.invisionapp.com/share/38S2U6FPFKD#/screens/359913354).

Since such feature doesn't exist in Chromium [(yet)](https://www.blog.google/products/chrome/building-a-more-private-web/), here's how I would suggest implementing this:

- Align to right with z-index (before or after page actions)
- Set the icon to [Chrome's built-in adblock](https://support.google.com/chrome/answer/7632919?co=GENIE.Platform%3DDesktop&hl=en)
- Make it appear on hover if disabled/not blocking on site
- Make it permanently appear if blocking

**Comment by locness3** [comment]
I also have the new panel on Firefox dev edition.
And for now the button looks like this :
![Screen Shot 2019-08-31 at 09 09 15](https://user-images.githubusercontent.com/37651007/64060575-0b506e00-cbcf-11e9-9681-f31f6adf712d.png)

**Comment by muckSponge** [comment]
I've aligned it before the page action buttons to ensure the star button remains at the end, and updated the icon to match Chrome's. Will close now but if you experience issues with it we can re-open.

**Comment by fmeyertoens** [comment]
@Madis0 I can't find the icon on the page that you linked. Which icon are you referring to?
@muckSponge I think this new icon looks way worse than the shield icon. What is it even supposed to mean? It doesn't look like anything. It opens "tracking protection". Why not use the shield icon then?

**Comment by Madis0** [comment]
Oh yeah, there is no icon on the page. On Chromium it looks like a window.

**Comment by muckSponge** [comment]
This is what it looks like in Chrome:
<img width="160" alt="image" src="https://user-images.githubusercontent.com/5405629/68468487-3c52bc00-026c-11ea-9da1-ad1eb18ba8b7.png">

I was only able to get it to show using a popup test (and blocking the popups) so I don't know if it's exactly the same for ads (I don't frequent any offending websites I guess). This is what the new icon is based on.

@fmeyertoens, do you know where I can find Chrome's shield icon in action? I do have a shield icon, which is currently unused: <img width="16" alt="image" src="https://user-images.githubusercontent.com/5405629/68468988-517c1a80-026d-11ea-8b0a-813296e23090.png">. Don't even remember what it was for but might be more suitable?

**Comment by Madis0** [comment]
The shield icon is for mixed content, such as https://mixed.badssl.com 
However, it will soon be moved to a "permission" so it may change icon, too.

**Comment by muckSponge** [comment]
Does Chrome still use it? I'm on 79 and can't see it anywhere when I head to https://very.badssl.com.

That shield icon isn't exactly appropriate either because it's either a shield or a shield with a red cross (which implies it is disabled or the protection is blocked, which makes no sense). Maybe we can use the shield icon (no cross) and colour it when it is blocking, like we do with the star button for bookmarked sites.

**Comment by Madis0** [comment]
[Yes, it doesn't exist in 79](https://security.googleblog.com/2019/10/no-more-mixed-messages-about-https_3.html). Try looking at page settings, there should be an option there.

> Maybe we can use the shield icon (no cross) and colour it when it is blocking, like we do with the star button for bookmarked sites.

I like that idea - gray if not blocking, blue if blocking.

**Comment by fmeyertoens** [comment]
I just thought that the firefox shield icon looked quite good for the job. Your shield icon also looks good and I can't find another shield icon on material.io.
I favor using the icon without the cross and color when blocking.
