### ISSUE TITLE
No spacing between tab and window border

### ISSUE THREAD

**Issue by navdeepio** [muckSponge/MaterialFox#148]
Here's what I see on macos X, firefox 68.0.2
<img width="764" alt="Screenshot 2019-08-28 at 4 17 40 PM" src="https://user-images.githubusercontent.com/9297865/63849446-bd115400-c9af-11e9-8050-4a022582c1fb.png">

But this is what's it's supposed to look like(from repo readme)
<img width="764" alt="Screenshot 2019-08-28 at 4 19 37 PM" src="https://user-images.githubusercontent.com/9297865/63849477-cb5f7000-c9af-11e9-8101-91b18b4b7ede.png">

**Comment by muckSponge** [comment]
Check out the recommended instructions in the readme, they should help you add that sexy space above the tabs.
