### ISSUE TITLE
Succesfully tested on Linux

### ISSUE THREAD

**Issue by Eddi2015** [muckSponge/MaterialFox#15]
As you said it's untested on Linux. Now it isn't any longer.
I just installed this on Manjaro Cinnamon and it works perfectly. No issues.

**Comment by muckSponge** [comment]
Thanks @Eddi2015! Would you be willing to add a screenshot here just so I can see how it looks? I'll close it regardless. Also updated README to reflect the fact that it has been tested as of today.

**Comment by Eddi2015** [comment]
I uploaded a screenshot with the light theme here: https://upload.disroot.org/r/LkHKtfrl#ItZdY6iXG3R4wmTRgu6vEnrHforU6/slHW1sVw1q9tw=

If you need a screenshot of the dark theme just tell me.
