### ISSUE TITLE
it does not fit with firefox version 69

### ISSUE THREAD

**Issue by melodicwang** [muckSponge/MaterialFox#151]
hope it will be  update soon   

love this plugin so much !

**Comment by TowelBin** [comment]
set `toolkit.legacyUserProfileCustomizations.stylesheets` to true in `about:config`

**Comment by muckSponge** [comment]
Thanks, @TowelBin. @melodicwang, does that resolve your problem? If you follow the steps in the [README](https://github.com/muckSponge/MaterialFox/blob/master/README.md) everything should work fine with Firefox 69.

If you're experiencing another problem you'll need to be more specific so we can help.

**Comment by melodicwang** [comment]
yeah, it is my mistake,i did not look up into the readme.
it is fine now
thank you so much
