### ISSUE TITLE
Style bug (Firefox >= v71)

### ISSUE THREAD

**Issue by xp4u1** [muckSponge/MaterialFox#154]
![issue](https://user-images.githubusercontent.com/29521470/66873209-312ba980-efa8-11e9-8c54-8637c884d8c6.png)

**Comment by montd** [comment]
![2019-10-16 01_24_28-](https://user-images.githubusercontent.com/33810914/66876925-dac46800-efb3-11e9-8e18-dda25ea8af67.png)

**Comment by Zoahr** [comment]
![Materialfox error](https://user-images.githubusercontent.com/44004296/66898177-eab26b00-eff8-11e9-962d-00a829004d10.jpg)

**Comment by redfoxseattle** [comment]
I'm having the same issue after upgrading to Firefox Developer Edition v. 71.

**Comment by Aire-One** [comment]
I can confirm #155 fix the style bug on tabs.

However, I'm running firefox-nightly and the latest update (71.0a1 (2019-10-21)) broke the URL bar (See screenshots).

Normal: ![cropped-2019-10-23-114942_1920x1080_scrot](https://user-images.githubusercontent.com/6602958/67381424-2f577c80-f58c-11e9-8ad6-85b038206a95.png)
Focused: ![cropped-2019-10-23-115143_1920x1080_scrot](https://user-images.githubusercontent.com/6602958/67381426-2ff01300-f58c-11e9-8db1-f14a46dd27de.png)
Suggestion: 
![2019-10-23-121618_1920x1080_scrot](https://user-images.githubusercontent.com/6602958/67383102-e05f1680-f58e-11e9-8b9a-7ad7989b5650.png)

Should I open a new issue (assuming firefox-nightly is supported) or this one will collect all style bugs (for version >= 71)?

**Comment by fmeyertoens** [comment]
This is the new megabar and the style issue for that is tracked here: https://github.com/muckSponge/MaterialFox/issues/150
