### ISSUE TITLE
minimize/close buttons are not perfect

### ISSUE THREAD

**Issue by Nover2** [muckSponge/MaterialFox#158]
On windows 10, minimize/close buttons are not perfect.
![图片](https://user-images.githubusercontent.com/46912250/67409296-f4d1fc00-f5ec-11e9-90cf-fb47bf9f1578.png)
![图片](https://user-images.githubusercontent.com/46912250/67409380-16cb7e80-f5ed-11e9-88bc-44e54ddb689e.png)

**Comment by fmeyertoens** [comment]
Which Firefox version are you using?
Any custom themes?
