### ISSUE TITLE
Use Chrome skins?

### ISSUE THREAD

**Issue by Ansem93** [muckSponge/MaterialFox#159]
Hi everyone, do you think it would be possible to add support to chrome skins?

**Comment by muckSponge** [comment]
If you're talking about your standard Chrome themes, as @Excigma mentioned, they aren't *technically* supported (you can't install from Chrome web store) but the themes are essentially composed in the exact same way now so you can get the author of the theme to upload it to [AMO](https://addons.mozilla.org/en-US/firefox/themes/) and you'll be able to use it (or if you're really desperate there's probably some way to obtain the theme and manually install it). This kind of theme is supported by MaterialFox but there are a few elements here and there which will differ from Chrome. Most notably, for very light themes, tabs won't have a border around them. For the most part though, they'll look very similar.

If you're talking about some other kind of theme then no, they won't be supported.

I'll close this now but happy to re-open if we didn't answer your question.
