### ISSUE TITLE
Issue template

### ISSUE THREAD

**Issue by fmeyertoens** [muckSponge/MaterialFox#160]
Is it possible to create an issue template for this repository?
I thought about something like

OS: ---
Firefox version: ---
Custom Themes: Yes/No/---
I read the installation instructions

Just because many people forget about that when raising an issue

**Comment by muckSponge** [comment]
Thanks for this suggestion - it's a good idea so I've implemented a template.

Users will need to explicitly check off 3 sanity checks when completing a bug report, so we avoid issues where people haven't followed the instructions, have made changes to the theme, or are using an outdated version. It's based on the default issue template which will prompt people to provide screenshots and steps to reproduce the problem.
