### ISSUE TITLE
Search bar is broken after updating to version 70

### ISSUE THREAD

**Issue by sdushantha** [muckSponge/MaterialFox#161]
As you see, there is something wrong. It worked perfectly in version 69, but when I updated to version 70 the search bar broke. Is it possible to fix this?
![Screenshot 2019-10-25 at 19 20 48](https://user-images.githubusercontent.com/27065646/67591037-bf4c2080-f75c-11e9-8d10-6579701e65fa.png)

OS: macOS
Firefox: 70.0 (64-bit)

**Comment by fmeyertoens** [comment]
See https://github.com/muckSponge/MaterialFox/issues/150

**Comment by sdushantha** [comment]
@fmeyertoens If I understand correctly, there is no fix for this yet, but it is being worked on by @arshwaraich12, right?

**Comment by fmeyertoens** [comment]
That's correct. I think Muck also did some work on it. But Firefox is getting a new search bar in one of the next releases anyway.

**Comment by muckSponge** [comment]
Dup of #150. Let's keep it in the same place :)
