### ISSUE TITLE
tab scrollbox was changed

### ISSUE THREAD

**Issue by fmeyertoens** [muckSponge/MaterialFox#162]
The `xul:scrollbox` was changed to `scrollbox part="scrollbox"` within the `arrowscrollbox` element.

Context (Before):
```html
<arrowscrollbox class="tabbrowser-arrowscrollbox">
  <xul:scrollbox class="arrowscrollbox-scrollbox">
    <tab>
    <tab>
    ...
    <toolbarbutton id="tabs-newtab-button" class="toolbarbutton-1"/></toolbarbutton>
  </xul:scrollbox>
</arrowscrollbox>
```

We have three css rules with the class `arrowscrollbox-scrollbox` but this class doesn't exist anymore on the new element. They need to be changed.

OS: Win10
Firefox version: 71.0b4 (Dev)

**Comment by muckSponge** [comment]
This should be fixed. Will close; let me know if the issue remains and I can re-open.
