### ISSUE TITLE
urlbar too big

### ISSUE THREAD

**Issue by fmeyertoens** [muckSponge/MaterialFox#166]
There was another item (#urlbar-background) added to the urlbar which increases the height.
```html
<hbox id="urlbar">
  <hbox id="urlbar-background">
  <hbox id="urlbar-input-container">
</hbox>
```
![ff-dev-urlbar-height-bug](https://user-images.githubusercontent.com/26410884/67666623-7b2f6a80-f96c-11e9-85e4-31797ba9e1a4.png)
This can easily be fixed by putting `display: none` on the new element but I don't know the purpose of this element yet and whether this breaks anything.
OS: Win10
FF Version:71.0b4 (dev)

**Comment by muckSponge** [comment]
I believe this is fixed now but let me know if it still occurs and we can re-open.
