### ISSUE TITLE
Container Tabs name in urlbar is misplaced

### ISSUE THREAD

**Issue by trbn1** [muckSponge/MaterialFox#167]
Container Tabs name in urlbar is misplaced, it is positioned wrongly before and after loading a website.
Blank new tab:
![firefox_2019-10-28_14-55-02](https://user-images.githubusercontent.com/12391889/67684229-13d8e100-f993-11e9-895e-b36607a030d0.png)
After loading a website:
![firefox_2019-10-28_14-55-22](https://user-images.githubusercontent.com/12391889/67684276-23582a00-f993-11e9-988d-bdfc4e72cc3e.png)
Also it's completely invisible after selecting the urlbar.

**Comment by LM1LC3N7** [comment]
Same here, the URL bar is not correct.

![image](https://user-images.githubusercontent.com/14235706/67684843-d1f86c80-f98b-11e9-8657-448808c99a06.png)

* Firefox 71.0b4 (64 bits)
* Last commit of [MaterialFox](https://github.com/muckSponge/MaterialFox/commit/a52e3a18fd7d09119ec8d014fd830b0375564d7a)

**Comment by ppperadam** [comment]
> Same here, the URL bar is not correct.
> 
> ![image](https://user-images.githubusercontent.com/14235706/67684843-d1f86c80-f98b-11e9-8657-448808c99a06.png)
> 
>     * Firefox 71.0b4 (64 bits)
> 
>     * Last commit of [MaterialFox](https://github.com/muckSponge/MaterialFox/commit/a52e3a18fd7d09119ec8d014fd830b0375564d7a)

I think I found a quick solution for this large URL bar. I just hacked it, so it's probably not the best way - but it fixes the issue temporarily.

urlbar.css, add this new code: 

`#urlbar-input-container, #searchbar {
    position: absolute !important;
	top: 6px !important;
}`

**Comment by ppperadam** [comment]
> @ppperadam did you try [#166 (comment)](https://github.com/muckSponge/MaterialFox/issues/166#issue-513187205)?

Nope - didn't realize that comment offered a solution. Appreciate it. That fixed it.

**Comment by LM1LC3N7** [comment]
Thanks @ppperadam, your solution worked like a charm!
