### ISSUE TITLE
Audio playing on tab looks blurry and overlaps with next tab

### ISSUE THREAD

**Issue by starzonmyarmz** [muckSponge/MaterialFox#168]
This doesn't look so great:

![Screen Shot 2019-10-30 at 2 07 52 PM](https://user-images.githubusercontent.com/171375/67885919-d5702d00-fb1e-11e9-8875-330a971b7997.png)

**Comment by muckSponge** [comment]
The default icon just isn't very good on different backgrounds. I've changed it to match Chrome's behaviour so you'll see just the icon (which is now Chrome-style) in pinned tabs, no favicon. There's basically no way to smush the icon in there without it overlapping something and looking cluttered so I think this should be fine unless you have multiple pinned tabs emitting sound, but that seems like a very unlikely scenario. It also now matches the close tab button's hover and pressed states.
