### ISSUE TITLE
Tracking Protection Icon Incorrectly Rendered

### ISSUE THREAD

**Issue by leogx9r** [muckSponge/MaterialFox#169]
With Firefox 70 and the recent fix to the urlbar, it renders properly if the icon isn't colored.
![Example](https://i.imgur.com/IBciXBw.png)

However, if it is colored, it renders the icon below where it should be:

![Example](https://i.imgur.com/Ad90eBM.png)

**Comment by muckSponge** [comment]
Just need to know how I can get that icon to appear coloured so I can reproduce.

**Comment by muckSponge** [comment]
Looks like a dup of #165.
