### ISSUE TITLE
Home button not working in Firefox Developer Edition

### ISSUE THREAD

**Issue by shscs911** [muckSponge/MaterialFox#170]
Clicking `Home` button or `Alt+Home` displays a blank page instead of the homepage.

New Tab: 
![New Tab](https://user-images.githubusercontent.com/44034402/68021537-ae089400-fcc7-11e9-854f-d377cde3c03a.png)

After Pressing Home Button:
![Home](https://user-images.githubusercontent.com/44034402/68021569-c7a9db80-fcc7-11e9-8989-c5c00a1d5df1.png)

OS: Arch Linux
DE: KDE Plasma 5.17.2
Firefox: Firefox Developer Edition 71.0b5 (64-bit)

**Comment by muckSponge** [comment]
Can you verify that the problem goes away after uninstalling MaterialFox?

**Comment by shscs911** [comment]
My homepage settings was pointing to `Firefox Home`, changing it to `Current Page` fixed the issue. Sorry for troubling you, keep up the good work.
