### ISSUE TITLE
Pop-ups have no background

### ISSUE THREAD

**Issue by redfoxseattle** [muckSponge/MaterialFox#171]
All of the pop-ups coming from my bookmarks or add-ons bar have no background. I'm using Firefox Developer on Mac OS Mojave.

![2019-11-01_10-40-06](https://user-images.githubusercontent.com/21209421/68044272-3cfbb900-fc94-11e9-979c-3adf29db9e1f.png)

**Comment by muckSponge** [comment]
I think this is a dup of #156 which was fixed in #157. The title in #156 is a bit too specific but essentially the same issue. Should be fixed though, so will close. I'll retitle #156 and close this. Any issues, please comment in #156.
