### ISSUE TITLE
Zoom indicator positioned too low

### ISSUE THREAD

**Issue by Excigma** [muckSponge/MaterialFox#172]
![image](https://user-images.githubusercontent.com/30280397/68082856-b9ee8480-fe86-11e9-83e1-8a97d889dceb.png)

Commit: https://github.com/muckSponge/MaterialFox/commit/2f6f7ce64ef9e0fba7caec177e2aca541f510476

Windows 10
Firefox 70.0.1 Stable 64 bit

**Comment by Excigma** [comment]
On this: https://www.pngtosvg.com/ site, this happens too:
![image](https://user-images.githubusercontent.com/30280397/68083081-79443a80-fe89-11e9-9580-6b2130175185.png)

**Comment by bucklingspring** [comment]
I've experienced both of these as well. 
![image](https://user-images.githubusercontent.com/32025806/68175324-b36b1600-ff35-11e9-8b0d-129c96ebe18c.png)

**Comment by muckSponge** [comment]
This seems to have resolved itself recently (tested 70 and 72). We're now styling the page action `toolbarbutton`s to match the other buttons and icons in the urlbar.
