### ISSUE TITLE
Default search behavior changes once theme is applied. It becomes a little "messy" 

### ISSUE THREAD

**Issue by yapja** [muckSponge/MaterialFox#182]

**Comment by muckSponge** [comment]
Going to need some more details before this can be worked on. I need Firefox version, OS, and a screenshot of the issue.

**Comment by yapja** [comment]
https://imgur.com/a/NDzg87L

Firefox version: 70.0.1 (64-bit)
OS version: 1809 (OS Build 17763.805)

**Comment by Excigma** [comment]
Do you have other theme or userChromes possibly interfering?

**Comment by Excigma** [comment]
![image](https://user-images.githubusercontent.com/30280397/68549079-15a5a880-0459-11ea-837d-1a675d8df369.png)

![image](https://user-images.githubusercontent.com/30280397/68549094-3e2da280-0459-11ea-9fce-65da1d6cdf26.png)

![image](https://user-images.githubusercontent.com/30280397/68549099-53a2cc80-0459-11ea-817a-15805be3ea02.png)

**Comment by yapja** [comment]
I have Shadowfox. Apparently, MaterialFox and Shadowfox being together messes up the color of the search bar.

**Comment by muckSponge** [comment]
Had to mark this as wontfix, unfortunately. Can't really guarantee support for other userChrome themes because they all use `!important` and try to override each other. If you're really keen to get this working you can manually find the offending element and set `background-color: transparent`.
