### ISSUE TITLE
URL/Search bar broken

### ISSUE THREAD

**Issue by Tunacan427** [muckSponge/MaterialFox#184]
**Sanity checks (must complete)**
- [X] I have read and followed the installation instructions in the README
- [X] I have not modified the userChrome.css file
- [X] I have tested the latest release or commit on master

**Describe the bug**
The search bar is sized very wrongly (see screenshot)

**To Reproduce**
1. Install the theme.

**Screenshots**
![Screenshot_20191109_180256](https://user-images.githubusercontent.com/29532856/68530647-3b2c9800-031b-11ea-9520-7fbecb58d32e.png)

**System info**
 - OS: Gentoo Linux
 - Firefox version: Nightly 68.2.0esr

**Comment by BlackTurtle69** [comment]
Only firefox 70+ is supported as much as Im aware. Support for old versions is droped.

**Comment by Tunacan427** [comment]
Okay, I will try installing Firefox 70. Thanks!

**Comment by Tunacan427** [comment]
Okay, it works with Firefox 70. Thanks!
