### ISSUE TITLE
Removing seperators / hiding the bookmarks bar

### ISSUE THREAD

**Issue by schoening** [muckSponge/MaterialFox#186]
Hi, very cool extension!
But while trying to hide the bookmarks bar I pressed the "New Seperator" button. 

![Screenshot 2019-11-09 at 20 00 17](https://user-images.githubusercontent.com/1976060/68533712-8bf8bc80-032c-11ea-99f5-afa461573bf5.png)

But I am unable to find a "remove seperator", or a hide bookmarks bar button for that matter.. 
Is there any documentation on this somewhere?
How can I accomplish these things?

**Comment by Madis0** [comment]
Right click on the separator itself and select Delete. That is not related to this theme...

**Comment by schoening** [comment]
Ohhh, I had to click more pixel perfect. Worked like a charm. Thank you. Closing.
