### ISSUE TITLE
URL Bar Text moves up when URL Bar is focused 

### ISSUE THREAD

**Issue by Excigma** [muckSponge/MaterialFox#187]
**Sanity checks (must complete)**
- [x] I have read and followed the installation instructions in the README
- [x] I have not modified the userChrome.css file
- [x] I have tested the latest release or commit on master

**Describe the bug**
The URL Bar's text gets moved up when the URL bar is focused

**To Reproduce**
1. Get the latest master
2. Select the URL bar

**Screenshots**
![8lbcGK9jnX](https://user-images.githubusercontent.com/30280397/68538691-a2128580-03dd-11ea-9992-d3f9f66e6785.gif)

![image](https://user-images.githubusercontent.com/30280397/68538702-bce4fa00-03dd-11ea-8b88-a2da2487ed9e.png)
![image](https://user-images.githubusercontent.com/30280397/68538703-c1a9ae00-03dd-11ea-854e-828e5c76a30c.png)
More noticeable with URL selected:
![image](https://user-images.githubusercontent.com/30280397/68538708-d9813200-03dd-11ea-8f5c-757548d77216.png)

**System info**
 - OS: Windows 10
 - Firefox version: 70.0.1 (64-bit)

**Comment by Madis0** [comment]
Very noticable on Linux (GNOME) even without highlighting.
![Kuvatõmmis 2019-11-14 19-37-32](https://user-images.githubusercontent.com/8611110/68881753-672e8b80-0716-11ea-8499-15a80946bf6c.png)
![Kuvatõmmis 2019-11-14 19-37-34](https://user-images.githubusercontent.com/8611110/68881756-6990e580-0716-11ea-9def-091408ff9afd.png)

**Comment by muckSponge** [comment]
Interestingly this doesn't occur on macOS AFAIK. Will have to wait until I have access to a Windows machine before I can fix, unless someone else wants to tackle it in the meantime.

**Comment by Human1895** [comment]
for me its always raised upwards (archlinux firefox stable)

**Comment by muckSponge** [comment]
Is this still an issue (Firefox 74+)? Never managed to reproduce it.

**Comment by Madis0** [comment]
![unfocused](https://user-images.githubusercontent.com/8611110/78432629-26f88700-767e-11ea-8570-7e12321095a2.png)
![focused](https://user-images.githubusercontent.com/8611110/78433149-4db6bd80-767e-11ea-9478-311c713699b8.png)
76.0a1 (2020-04-03)

**Comment by Excigma** [comment]
I am not able to see if it still can be reproduced with plain sight anymore, The URL suggestion dropdown opens on focus, so either it's gone, or not noticeable?
