### ISSUE TITLE
URL bar button dropdowns moving when placing mouse on them

### ISSUE THREAD

**Issue by locness3** [muckSponge/MaterialFox#190]
**Sanity checks (must complete)**
- [x] I have read and followed the installation instructions in the README
- [x] I have not modified the userChrome.css file
- [x] I have tested the latest release or commit on master

**Describe the bug**
Because all the buttons in the url bar slide to the right when the mouse isn't on the url bar, all dropdowns opened from these do the same when you move your mouse outside the url bar.
![ezgif com-video-to-gif(1)](https://user-images.githubusercontent.com/37651007/68946802-21c09b80-07b4-11ea-9cdd-dbc0e24b3c12.gif)

**To Reproduce**
1. Click any menu button in the url bar that has a dropdown menu
2. Observe the menu moving away as you get your mouse on it.

**System info**
 - OS: macOS 10.11.6
 - Firefox version: 70.0.1

**Comment by muckSponge** [comment]
Please test 6141249 when you get a chance.

**Comment by locness3** [comment]
Works perfectly.
