### ISSUE TITLE
Folders in Bookmarks Toolbar cannot be closed when clicking on them again

### ISSUE THREAD

**Issue by jonschlu** [muckSponge/MaterialFox#191]
I have a few folders in my Bookmarks Toolbar. When clicking on one, the list with all bookmarks contained shows up. However, when clicking on the folder again, it doesn't close the list, it does nothing. Only clicking somewhere else will close the list/folder. 
I often click on a folder to peak inside it and click at the same spot to close the list again, so it's weird when it doesn't work; I assume it's a bug.

**Comment by muckSponge** [comment]
Please test 98e51c4 to ensure the issue is resolved.

**Comment by jonschlu** [comment]
I downloaded and integrated the latest master and it appears to have fixed the issue – folders in the bookmarks toolbar now close when you click on them again.
