### ISSUE TITLE
Title bar text is abnormal when Firefox is updated

### ISSUE THREAD

**Issue by aD4wn** [muckSponge/MaterialFox#194]
Like this
![Image](https://user-images.githubusercontent.com/31566379/70366709-510a8a00-18d4-11ea-803a-7e573dc3408c.png)
At the same time, I also noticed that the about: preferences and about: addons pages are incomplete.

**Comment by muckSponge** [comment]
Can you please provide the Firefox version and OS?

**Comment by Pankrakles** [comment]
I'm also having this issue, running Windows 10 and firefox version 71.0

**Comment by aD4wn** [comment]
> 
> 
> Can you please provide the Firefox version and OS?

Firefox 72.0 b11 and Windows10

**Comment by muckSponge** [comment]
I'm unable to reproduce this behaviour, testing on 71 and Windows 10. Are you using a HiDPI screen setting (e.g. your display scale is at least 200%)? Your new tab icon is blurry which is why I'm asking.

Perhaps try the theme on a fresh profile and see if the problem persists.

**Comment by aD4wn** [comment]
When my Firefox automatically updated to 73.0b2 today, MaterialFox works well, the only problem is the search bar
