### ISSUE TITLE
Search suggestions nearly overlap with search engine name

### ISSUE THREAD

**Issue by shscs911** [muckSponge/MaterialFox#198]
**Sanity checks (must complete)**
- [x] I have read and followed the installation instructions in the README
- [x] I have not modified the userChrome.css file
- [x] I have tested the latest release or commit on master

**Describe the bug**
When searching from address bar `Search with ...` appears too close to search suggestions.

**To Reproduce**
1. Search for something
2. See the search suggestions

**Screenshots**
![MaterialFox](https://user-images.githubusercontent.com/44034402/71060366-4b8e2900-218b-11ea-99e0-4fcfecb2a3e3.png)

**System info**
- OS: Arch Linux
- DE: KDE Plasma 5.17.4
- Firefox: Firefox Developer Edition 72.0b7 (64-bit)

**Comment by muckSponge** [comment]
Should be fixed in 3201477. Completely changed how the layout works so there may be more issues for some edge cases.

**Comment by kulocora** [comment]
> 
> 
> Should be fixed in [3201477](https://github.com/muckSponge/MaterialFox/commit/3201477b457e0f7a092182e7749729472d0c420d). Completely changed how the layout works so there may be more issues for some edge cases.

![图片](https://user-images.githubusercontent.com/12947678/71183838-a4f17780-22b3-11ea-897d-31ab891ad50f.png)
Completely broken now ;(

**Comment by muckSponge** [comment]
Ah ok didn't test 72. They've probably rearranged all the DOM again.

**Comment by muckSponge** [comment]
I was going to make a 72 branch for this because the DOM layout is different compared to 71. I ran out of free time to work on this in the last 2 weeks and 72 becomes stable in a few days so I'll try to have a commit ready by then.

**Comment by muckSponge** [comment]
This specific issue has been resolved so I'll close it. Any further discussion can probably go in #201.
