### ISSUE TITLE
Not working in Windows

### ISSUE THREAD

**Issue by ovasquez** [muckSponge/MaterialFox#2]
Thanks for the great theme, the screenshot looks amazing!

I'm having problems using it on Windows, below are the details.
Please let me know if there's anything I can help with to get this fixed, I don't know if this could be related to my machine only or something general for Windows users.

### System Details
- Windows 10
- Tested on Firefox 61 and Firefox Developer Edition 63.0b1

### Current visual behavior
![image](https://user-images.githubusercontent.com/7527242/44886043-5dd81100-ac81-11e8-8bc3-e1cc72047b71.png)

**Comment by muckSponge** [comment]
Looks like you may have missed one of the installation steps. Go to about:config (in address bar), search for: ```svg.context-properties.content.enabled``` and set it to true. By default, Firefox doesn't allow SVG graphics (the icons, tabs, etc.) to have their colour set through CSS. This setting fixes that.

**Comment by ovasquez** [comment]
You are absolutely right. Thanks for the awesome theme!

**Comment by muckSponge** [comment]
No problem, thanks for using it and the informative issue post, good form!

**Comment by vuvansang07** [comment]
Your theme have a little problem
1: in a drop down menu list url
You using a trick make background is transparent:
#urlbar-results { background: 0 !important; } 

But background still there, so if you click mouse in area of background, url result list menu not hide. 

How to make background is "real hidden"? 

2: how to make url result menu list width = url bar (search bar)  width dynamically. 
When you customize more item, the calc(var(--item-padding-first) - var(--item-padding-end)) not working
I can fix size by manual, but i hope have a nice way to fix this. 

3: In firefox quantum 67, when swith: tím
to tìm by switch: s key and f key, url bar not effect (border hidden) and just using default state (default state: border color blue). 
And url result menu is reload when switch. 
But in firefox 68 developer, it is normal

I just spend 2 days to make MaterialFox to Flat UI like Edge, i like it, but have any problem i can't fix with my knowledge, please help me if you can, tkanks

Link Flat Theme Guide: repl.it/@ifree/firefox
