### ISSUE TITLE
URL bar too big on Firefox 68.3.0esr

### ISSUE THREAD

**Issue by edricus** [muckSponge/MaterialFox#200]
**Sanity checks (must complete)**
- [✓] I have read and followed the installation instructions in the README
- [✓] I have not modified the userChrome.css file
- [✓] I have tested the latest release or commit on master

**Describe the bug**
Url bar is too big 

**To Reproduce**
1. Install the theme on Firefox 68.3.0esr 

**Screenshots**
![bug](https://i.imgur.com/2zLJ5O0.png)

**System info**
 - OS: Debian 10 kernel 5.3.0-2-amd64
 - Firefox version: 68.3.0esr

**Additional context**
It would be nice to add a branch for ESR version of Firefox.

**Comment by muckSponge** [comment]
Am I right in thinking ESR won't really change until [Q3 2020](https://wiki.mozilla.org/Release_Management/Calendar)?

It's going to be a difficult, messy process to branch from a 68 commit and cherry pick newer bug fixes and features while maintaining 68 compatibility.

In case I don't get around to this, you can try commit caa72cf8aacf3a00cd85073c2bf3bf06c67ef979. This contains the last bug fix I applied for 68, which implies it is compatible with 68. Won't have many of the newer bug fixes though. A _lot_ changed between 68 and 72 so probably at least half the commits are just fixing regressions, sprinkled with some improvements.

Moving forward I'll probably have a branch for each major Firefox version and just update the default branch to point to the latest stable version branch. That way, you'll be able to locate the correct branch based on your ESR version.

**Comment by muckSponge** [comment]
I've marked as wontfix. If you try caa72cf you might find it resolves the problem but the DOM has changed dramatically between 68 and 72+ so if you want support for ESR moving forward, you'll have to wait until Q3 2020. Probably not what you're wanting to hear but a few more months and it should be compatible again, and I'm creating incremental branches so this shouldn't be a problem in the future.
