### ISSUE TITLE
Is it impossible to customize?

### ISSUE THREAD

**Issue by hrqmonteiro** [muckSponge/MaterialFox#203]
Why is it that no matter what variable i edit in the .css files (light mode or dark mode, or default) it remains exactly the same? Is it impossible to edit the colors of the theme to match my personal choices for color scheme? Is the color variables in the files useless? 
I am literally not getting it. I went through all the files (global.css, variables.css and so on on the other folders), my firefox is looking exactly the same as when i downloaded the materialfox and put on the chrome folder

**Comment by muckSponge** [comment]
Try Firefox Color. The theme is set up to use the built in themes' colours.

It should be possible to do it manually in variables.css so long as you don't have a built in theme or Firefox Color (or similar add-on) installed.
