### ISSUE TITLE
(Bug?)[Query] Possible to retain small coloured bar below every container tab?

### ISSUE THREAD

**Issue by iamthekings5** [muckSponge/MaterialFox#204]
**Describe the bug**
Right now only the coloured container bar is displayed below the tab in the forefront, but I was wondering if there was a way for every bar for every container tab to be shown, be it in the forefront or background. I have tried editing some settings in the tabbar.css file to no avail. The furthest I have gotten is the bars being shown, but they disappear when you hover over them.

**System info**
 - OS: [e.g. Windows 10]
 - Firefox version: [e.g. 72]

**Comment by Write** [comment]
I would love too having the bar below being shown.
Unfortunatly, I tried in vain

**Comment by berkcodes** [comment]
+1 It'd be really nice to see the indicator as it makes it easy to identify the tabs and also adds some colour.
