### ISSUE TITLE
Ctrl+F search box text is not visible in private windows

### ISSUE THREAD

**Issue by manasrawat** [muckSponge/MaterialFox#205]
In private windows, the colour of the text in the Ctrl+F search box is white - the same colour as the box itself is, resulting in the search box's text not being visible (until the searched-for phrase isn't found in the web page, which changes the search box colour, as expected). Thanks.

**Comment by muckSponge** [comment]
I've styled the search box now so this should be fixed.

**Comment by kidonng** [comment]
This issue seems to reappear on my Firefox 79.0 (style is latest 80.0 tag):

![](https://user-images.githubusercontent.com/44045911/90259632-eeaf5380-de7c-11ea-8de7-6c15d4363fb9.png)
