### ISSUE TITLE
URL bar style issue

### ISSUE THREAD

**Issue by A1U** [muckSponge/MaterialFox#208]
![Bug.jpg](https://i.loli.net/2020/02/14/uVG4POFwBj1d8oT.jpg)
Here is the screenshot, look the left and right red rectangles, why there are two blank space.
The URL bar should be align to left.

**Comment by muckSponge** [comment]
Right click on the toolbar, select Customise and drag those spaces out of the toolbar. It's not a bug in the theme; it's just personal preference and how the Firefox nav bar is set up by default. The theme itself doesn't need to change it because Firefox allows you to do that through its own UI ;)
