### ISSUE TITLE
Bookmarking-popup has incorrect padding on macOS Mojave.

### ISSUE THREAD

**Issue by mikkelpetersen** [muckSponge/MaterialFox#210]
**Sanity checks (must complete)**
- [X] I have read and followed the installation instructions in the README
- [X] I have not modified the userChrome.css file
- [X] I have tested the latest release or commit on master

**Describe the bug**
The popup when bookmarking a website has incorrect padding.

**To Reproduce**
1. Go to any website.
2. Bookmark the website.
3. The popup that shows has incorrect padding.

**Screenshots**
[![Screenshot-2020-03-04-at-22-39-20.png](https://i.postimg.cc/hvfZ0NnJ/Screenshot-2020-03-04-at-22-39-20.png)](https://postimg.cc/zHYkztV5)

**System info**
 - OS: macOS 10.14.6 (macOS Mojave)
 - Firefox version: 73.0.1

**Additional context**
Let me know, if you need any additional information.

**Comment by muckSponge** [comment]
This should be fixed in 4c73c060476a8d3b25a01d7417eba17c1e1ff201.
