### ISSUE TITLE
Icons modified by theme are broken in FF 75.0b4

### ISSUE THREAD

**Issue by Vigasaurus** [muckSponge/MaterialFox#212]
**Sanity checks (must complete)**
- [X] I have read and followed the installation instructions in the README
- [X] I have not modified the userChrome.css file
- [X] I have tested the latest release or commit on master (on both 72 and 74 branches)

**Describe the bug**
Icons that are modified by the theme (in my instance all but the Synced Tabs and the Overflow Menu) are not loading correct colors or SVGs (or there is a extra SVG being loaded). 

I've tried modifying them with Firefox Color and trying all the default themes + resetting all settings to default, as well as a fresh profile - problem still persists. 

**To Reproduce**
1. Setup theme on FF 75.0b4

**Screenshots**
![image](https://user-images.githubusercontent.com/19434157/76869532-78a7b180-6836-11ea-80db-077a05228b81.png)

**System info**
 - OS: Windows 10
 - Firefox version: 75.0b4

**Comment by muckSponge** [comment]
You need to set svg.context-properties.content.enabled to true (see [README](https://github.com/muckSponge/MaterialFox/blob/74/README.md)).

**Comment by Vigasaurus** [comment]
Ah right, thanks! The 75 update for some reason reverted this for me.
