### ISSUE TITLE
URL bar text clipped when typing 

### ISSUE THREAD

**Issue by thisispiggy** [muckSponge/MaterialFox#213]
**Sanity checks (must complete)**
- [x ] I have read and followed the installation instructions in the README
- [x ] I have not modified the userChrome.css file
- [x ] I have tested the latest release or commit on master

**Describe the bug**
When typing in url bar, the text is clipped off at the beginning.

**To Reproduce**
1. Open firefox
2. Type in URL

**Screenshots**
https://imgur.com/cQzCQDA

**System info**
 - OS: Windows 10
 - Firefox version: 74.0

**Comment by Alexander-Huang** [comment]
Arch Linux,Firefox 74 with the same issue.The fonts seems garbled.
My font is Noto-Sans-cjk-sc-regular.

**Comment by muckSponge** [comment]
The issue in the screenshot isn't a font/text-related issue but the layout is completely wrong (so text has no padding around it). Assuming you both have the same issue, this sounds like there's some setting or opt-in feature you've enabled which isn't enabled by default.

If you can, please try a clean profile with a fresh install of MaterialFox and see if the problem persists.

**Comment by muckSponge** [comment]
Wait, are you guys on 74 branch or 72 branch? I think 72 branch had some of these issues if I recall correctly, so might just be that you need to update to 74.

**Comment by thisispiggy** [comment]
Oh ok yeah I was on master branch. Updated to 74 and I guess master branch now too. Things are fixed. Thank you so much.
