### ISSUE TITLE
Searchbar result panel has no background

### ISSUE THREAD

**Issue by feinir** [muckSponge/MaterialFox#215]
![批注 2020-04-04 203407](https://user-images.githubusercontent.com/10486636/78450840-0f3bf580-76b4-11ea-9e89-e58c34b4eda6.jpg)

**Comment by jelgerpostma** [comment]
Also having issues with the search box using Ctrl+F to find text in a page.

![image](https://user-images.githubusercontent.com/45315251/78529197-a39b7a80-77d0-11ea-8312-427b5916bfe8.png)

**Comment by muckSponge** [comment]
Should be fixed in da3125f. Styling isn't great but it's functional. Searchbar results panel is very resistant to layout changes.

**Comment by Zoahr** [comment]
Don't know if it's the same issue, but the right-click context menu is also missing the background
![Screenshot](https://user-images.githubusercontent.com/44004296/78754721-42aea680-7978-11ea-8530-617f21b6a344.png)

**Comment by muckSponge** [comment]
Oh no... that's a doozy. I'll look into it!

**Comment by muckSponge** [comment]
That menupopup missing background issue is referenced in #156 (try 76 branch; might rename it to beta, so look for 76 or beta), and the other issues have been resolved so I'll close this. If the search bar issues are not resolved for you on master, I'll reopen this issue.
