### ISSUE TITLE
Security warning

### ISSUE THREAD

**Issue by LoryAlvy** [muckSponge/MaterialFox#217]
When I try to download your file, a security warning appears.
Here is the message: 

**Connection broken: potential security risk

Firefox has detected a potential security threat and broken the connection with codeload.github.com, as it is only possible to connect to this site securely.

What can I do to fix it?

codeload.github.com uses a security policy called HTTP Strict Transport Security (HSTS). This means that Firefox can only connect securely and it is not possible to add an exception to visit this site.

The error is probably caused by the website and cannot be resolved.

If you are using a corporate network or antivirus software, contact the support teams for assistance. You can also report the problem to the website operator.**

Could you try to fix it?

**Comment by muckSponge** [comment]
This is probably a configuration problem on your end. See [here](https://support.mozilla.org/en-US/kb/secure-connection-failed-firefox-did-not-connect) for more information. 

Do you have security software installed? It might be interfering.

**Comment by muckSponge** [comment]
I've tested on two computers with Firefox Stable and Beta (74 and 75) and have had no issues downloading.

This is either an issue with your computer or an issue with GitHub, but it's not really related to the theme.

Are you clicking the [clone or download button](https://github.com/muckSponge/MaterialFox/archive/master.zip)? Have you tried downloading one of the [releases](https://github.com/muckSponge/MaterialFox/releases)? Have you tried using a different computer?

**Comment by LoryAlvy** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  And can you let gh know?                                                                                                                                              Inviato con Posta in arrivo di BlackBerry Hub+ per Android                                                                                                                                                                           Da: notifications@github.comInviato: 7 Aprile 2020 15:28A: MaterialFox@noreply.github.comRispondi a: reply@reply.github.comCc: l.alvarez@itsrizzoli.it; author@noreply.github.comOggetto: Re: [muckSponge/MaterialFox] SECURITY WARNING (#217)  
I've tested on two computers with Firefox Stable and Beta (74 and 75) and have had no issues downloading.
This is either an issue with your computer or an issue with GitHub, but it's not really related to the theme.
Are you clicking the clone or download button? Have you tried downloading one of the releases? Have you tried using a different computer?

**Comment by Vigasaurus** [comment]
https://support.github.com/contact

This isn't an issue with this repo at all, try getting in touch with Github support (link above) to find out if the issue is from your security settings, or GH's servers - and what the fixes may be. None of us can really do anything 🤷‍♂

**Comment by LoryAlvy** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  Ok, thanks, bdw, can u send me the file here in email?                                                                                                                                              Inviato con Posta in arrivo di BlackBerry Hub+ per Android                                                                                                                                                                           Da: notifications@github.comInviato: 8 Aprile 2020 16:00A: MaterialFox@noreply.github.comRispondi a: reply@reply.github.comCc: l.alvarez@itsrizzoli.it; author@noreply.github.comOggetto: Re: [muckSponge/MaterialFox] SECURITY WARNING (#217)  

https://support.github.com/contact

This isn't an issue with this repo at all, try getting in touch with Github support (link above) to find out if the issue is from your security settings, or GH's servers - and what the fixes may be. None of us can really do anything 🤷‍♂

**Comment by muckSponge** [comment]
Your best bet is to (ironically) download with Chrome or Safari. If you still have the issue, try cloning through git. I'd recommend something like [Fork](https://fork.dev/home) or one of [these other git GUIs](https://git-scm.com/downloads/guis).
