### ISSUE TITLE
Missing three-dots menu in awesome bar

### ISSUE THREAD

**Issue by heubergen** [muckSponge/MaterialFox#22]
This one is missing:
![screen shot 2018-09-17 at 18 22 53](https://user-images.githubusercontent.com/5529410/45635967-b6434700-baa6-11e8-9791-b560f3d0c036.png)

I'm not sure if this is intentionally or not.

**Comment by harpreetsb** [comment]
came here to say that exactly

**Comment by muckSponge** [comment]
It was intentional but in hindsight I may have been a bit too aggressive in hiding Firefox-specific features in order to replicate Chrome's look. I'll think about how I can integrate this back into the theme.

**Comment by harpreetsb** [comment]
How soon can we get this?

**Comment by muckSponge** [comment]
Resolved in ab811a0646871c2381c172aca9ed99275e425696.

**Comment by muckSponge** [comment]
Note that it will appear when you hover over the urlbar. It was a trade-off between retaining Firefox's features and looking like Chrome.

**Comment by harpreetsb** [comment]
Thank you very much.

**Comment by heubergen** [comment]
Thanks for the quick fix. 

PS: You could leave the issue open until the creator of the issue verifies that the bug is fixed for him now b but that just a suggestions.

**Comment by TwisterMc** [comment]
I feel that retaining Firefox's features should always be more important than looking like Chrome. Please don't limit Firefox.
