### ISSUE TITLE
[Suggestion] Include a user.js file

### ISSUE THREAD

**Issue by NICHOLAS85** [muckSponge/MaterialFox#220]
Instead of making users edit these settings themselves in `about:config` they'd just have to drop a user.js file in their profile folder, the same directory their chrome folder is dropped in. Then the recommended configuration options can be uncommented as wanted and a user is able to see exactly what has been configured for MaterialFox.

Here's an example file:
<details>
<summary>user.js</summary>

```js
/*** MaterialFox ***/
/**  Mandatory	  **/
user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true); // default is false
user_pref("svg.context-properties.content.enabled", true); 				// default is false

/**  Recommended  **/
/* Replicate Chrome behaviour for clipped tabs */
//user_pref("browser.tabs.tabClipWidth", 83); 							// default is 144

/* Allow tabs to shrink more; tabs in overflow will look the same as pinned tabs */
//user_pref("materialFox.reduceTabOverflow", true);

/* Replicate Chrome's "Not Secure" text on HTTP */
//user_pref("security.insecure_connection_text.enabled", true);
```

</details>

**Comment by muckSponge** [comment]
Finally got around to doing this. Hope it works...

**Comment by muckSponge** [comment]
Tested on a new profile – seems to work. Thanks for the suggestion!

**Comment by NICHOLAS85** [comment]
Hey just noticed something which may be helpful if you ever get issues related to uninstallation. It seems any changes done in the `user.js` file stick around even when the file is removed. So in order to completely uninstall MaterialFox they'd either have to hunt down those changes in `about:config` or you could suggest they change the values to their defaults in the `user.js` file and launch Firefox once before removing it.
Just a heads up!
