### ISSUE TITLE
Right click menu broken all the time.

### ISSUE THREAD

**Issue by SkyYkb** [muckSponge/MaterialFox#222]
**Sanity checks (must complete)**
- [X] I have read and followed the installation instructions in the README
- [X] I have not modified the userChrome.css file
- [X] I have tested the latest release for my Firefox version, or commit on master/beta branch (beta is for Firefox Beta only)

**Describe the bug**
Background color of right click menu turns to transparent.

**To Reproduce**
1. Just import MaterialFox to Firefox.

**Screenshots**
<img width="632" alt="image" src="https://user-images.githubusercontent.com/44992049/79062978-3c4e6080-7cd1-11ea-9e8d-566e4b9d23ec.png">

**System info**
 - OS: macOS Catalina 10.15.4
 - Firefox version: Firefox Nightly 77.0a1 (2020-04-11) (64-bit)

**Comment by muckSponge** [comment]
Try the beta branch. It's not in master yet because master is only guaranteed compatible with current stable Firefox version (which is 75 as of writing).

**Comment by SkyYkb** [comment]
Thanks a lot, problem solved with files in beta branch.
