### ISSUE TITLE
UrlBar outline overflows into bookmark toolbar items

### ISSUE THREAD

**Issue by trevarj** [muckSponge/MaterialFox#224]
**Sanity checks (must complete)**
- [x] I have read and followed the installation instructions in the README
- [x] I have not modified the userChrome.css file
- [x] I have tested the latest release for my Firefox version, or commit on master/beta branch (beta is for Firefox Beta only)

**Describe the bug**
UrlBar glow overflows into bookmark toolbar items.

**To Reproduce**
1. Have bookmark toolbar enabled and filled with links/folders
1. Click the address/url bar so that the url is highlighted
2. Hit the Esc key so that dropdown disappears
3. Notice that the outline of the urlbar is overflowing into bookmark toolbar items

**Screenshots**
![image](https://user-images.githubusercontent.com/5448324/79349265-b6cfe800-7f3e-11ea-89e7-ce4c046b8691.png)

**System info**
 - OS: Windows 10
 - Firefox version: 75

**Additional context**
Density set to "Compact" in customization.

**Comment by muckSponge** [comment]
I can't replicate on macOS. Will try Windows 10 when I get a chance.

**Comment by muckSponge** [comment]
Can't reproduce on Windows 10 (though I'm testing beta right now). Do you have any action buttons in the urlbar (far right of urlbar)?

**Comment by trevarj** [comment]
![image](https://user-images.githubusercontent.com/5448324/79630490-67fe9a00-815a-11ea-9198-7a8059d9dfaa.png)

I can try to install the beta and check it.

**Comment by trevarj** [comment]
Ok, it is fixed on beta. Thanks.
