### ISSUE TITLE
Close, minimize and fullscreen buttoms are one pixel too low.

### ISSUE THREAD

**Issue by Gagnef03** [muckSponge/MaterialFox#225]
**Sanity checks (must complete)**
- [X] I have read and followed the installation instructions in the README
- [X] I have not modified the userChrome.css file
- [X] I have tested the latest release for my Firefox version, or commit on master/beta branch (beta is for Firefox Beta only)

**Describe the bug**
Close, minimize and fullscreen buttons are one pixel too low, making it impossible to press them when you move your cursor to the top of the screen.

**To Reproduce**
1: Install the theme
![TNyiFZetlo](https://user-images.githubusercontent.com/46574798/79360325-0d8bf080-7f44-11ea-994f-372eb831b0fb.gif)

**Screenshots**
Add screenshots to help explain your problem.

**System info**
 - OS: [Windows 10]
 - Firefox version: [75]

**Comment by Excigma** [comment]
Can reproduce, Windows 10, Firefox 76

**Comment by ilindaniel** [comment]
Can not confirm, working fine on my side on Win 10 and Firefox 75

**Comment by muckSponge** [comment]
Able to reproduce. Only occurs when drag space is unchecked.
