### ISSUE TITLE
No background on personal bar folders

### ISSUE THREAD

**Issue by Minteck** [muckSponge/MaterialFox#226]
When you open a folder on the personal bar, the background of the list is transparent.

**Comment by muckSponge** [comment]
Need some more info on this:
- What version of MaterialFox are you using?
- What Firefox version are you using?
- What's your OS?

**Comment by p0358** [comment]
* Latest commit from master
* Firefox 76.0b7
* Windows 10 1909

@muckSponge latest Firefox beta version seems to make all context menus transparent with MaterialFox

**Comment by muckSponge** [comment]
Try the beta branch. I should really add something to the README to let people know to use the beta branch or releases if they're using Firefox Beta.

**Comment by p0358** [comment]
Right, that works. I should had checked the branches before asking tbh. But yup, the info in README would be good for clarity
