### ISSUE TITLE
transparency problem of context menu

### ISSUE THREAD

**Issue by Jacobax** [muckSponge/MaterialFox#229]
![1](https://user-images.githubusercontent.com/23228895/81081732-e57d2500-8f24-11ea-81ee-c4600e1e3df6.png)
![2](https://user-images.githubusercontent.com/23228895/81081745-e910ac00-8f24-11ea-8965-1ea3e91e5e05.png)

Firefox version 76.0 64bit

**Comment by Rhevin** [comment]
same issue in macOS Firefox 76.0 64bit

**Comment by fmeyertoens** [comment]
Try the beta branch. It is not yet merged into master.
https://github.com/muckSponge/MaterialFox/issues/226#issuecomment-618216644

**Comment by ML-Chen** [comment]
Beta branch resolves the issue for me.

**Comment by privacyguy123** [comment]
This is a FireFox 76 bug not a Beta bug.

**Comment by muckSponge** [comment]
If you check the releases section, you'll see which release to use for which version of Firefox. In this case, there's a fix in one of the v76 releases, which is for Firefox 76. Firefox 76 used to be in beta but was recently moved to stable. The MaterialFox beta branch is for beta versions of Firefox but of course the betas eventually become stable and the master (stable) branch needs to be periodically rebased on beta. In this case I've been a bit slow to do the rebase.
