### ISSUE TITLE
(Bug) Drag in tabs over each other leaves tabs with bold titel 

### ISSUE THREAD

**Issue by heubergen** [muckSponge/MaterialFox#23]
A short movie says more than thousands words...
https://youtu.be/VYoWlDjgXEk

**Comment by muckSponge** [comment]
Could you please verify that this doesn't happen with a clean userChrome.css file? I can't think of anything in my code which could cause this behaviour.

**Comment by heubergen** [comment]
I'm unable to reproduce the issue anymore. It might was an issue with Firefox Nightly even though I tested it without any chrome.css at all. I'll close the issue now.

**Comment by muckSponge** [comment]
Thanks. If you can reproduce it at a later time, feel free to re-open the issue.
