### ISSUE TITLE
Ctrl F icon broken in dark theme

### ISSUE THREAD

**Issue by codic12** [muckSponge/MaterialFox#231]
I'm on firefox 76 on manjaro linux. Here's how the find bar (ctrl f) looks with a dark theme:
![image](https://user-images.githubusercontent.com/48339289/81427904-4d439380-9110-11ea-8e54-1074830039f8.png)
As you can see, the search icon is dark when it should be light. Works fine with a light theme - would anyone happen to have any ideas on how to fix this? Using the latest version of materialfox. thanks

**Comment by gsbhasin123** [comment]
sanity checks:
 - [x]I have read and followed the installation instructions in the README
 - [x] I have not modified the userChrome.css file
 - [x] I have tested the latest release for my Firefox version, or commit on master/beta branch (beta is for Firefox Beta only)
