### ISSUE TITLE
Bookmark folder background invisible when opening

### ISSUE THREAD

**Issue by Bogghi** [muckSponge/MaterialFox#233]
Hi,
today I've update to firefox 76 and my bookmark folder turn invisible.

Screenshot: https://prnt.sc/sdeb6i

Thanks for this amazing theme btw.

**Comment by feinir** [comment]
![图片](https://user-images.githubusercontent.com/10486636/81507543-ccafad80-9330-11ea-8a8c-c31a0176e72c.png)

and right button menu

![图片](https://user-images.githubusercontent.com/10486636/81507569-e6e98b80-9330-11ea-8ec8-4b690ce1808d.png)

**Comment by sticsk** [comment]
Same thing here too, on Windows 10 (2 PCs) and also Manjaro

**Comment by ConfusedOwlet** [comment]
I had this as well, but reinstalling MaterialFox (using the master branch version rather than release version) seemed to have fixed it. Either that or it was fixed from one of the tweaks I added.

**Comment by Grogs** [comment]
Reinstalling MaterialFox (with v76.2) fixed this for me. 👍

**Comment by sticsk** [comment]
Yep, everything's alright now

**Comment by Bogghi** [comment]
I can confirm, installing material fox from the master branch it fixed the issue
