### ISSUE TITLE
Right click menus are transparent

### ISSUE THREAD

**Issue by rdivanji** [muckSponge/MaterialFox#235]
**Sanity checks (must complete)**
- [X] I have read and followed the installation instructions in the README
- [X] I have not modified the userChrome.css file
- [X] I have tested the latest release for my Firefox version, or commit on master/beta branch (beta is for Firefox Beta only)

**Describe the bug**
Right click menus are transparent.

**To Reproduce**
Download latest files from source, move over to profile folder, update to latest Firefox revision. Launch FF and right click, menus are transparent.

**Screenshots**
[Against a white background](https://i.imgur.com/wTsdBT6.png)
[Against some text](https://i.imgur.com/ItkbYHn.png)

**System info**
 - OS: Windows 10 1909
 - Firefox version: 76.0.1

**Additional context**
Commenting out `@import "popup/popup.css";` in the userChrome.css file fixes the issue but I know that's not a very specific or particularly helpful fix from a development perspective.

**Comment by sanneterpstra** [comment]
Reinstall of the master branche seems to fix this issue.

**Comment by rdivanji** [comment]
Okay well that fixed it!
