### ISSUE TITLE
urlbar suggestions window width jumps around when typing

### ISSUE THREAD

**Issue by mustaqimM** [muckSponge/MaterialFox#237]
**Sanity checks (must complete)**
- [x] I have read and followed the installation instructions in the README
- [x] I have not modified the userChrome.css file
- [x] I have tested the latest release for my Firefox version, or commit on master/beta branch (beta is for Firefox Beta only)

**Describe the bug**
When searching, the urlbar suggestions window width jumps around when typing.

**To Reproduce**
1. Start typing

**Screenshots**
[MaterialFox](https://streamable.com/u8wscv)
[Other](https://streamable.com/694g9n)

**System info**
 - OS: linux
 - Firefox version: 80

**Comment by Aire-One** [comment]
duplicates of https://github.com/muckSponge/MaterialFox/issues/223

Your video is great to show the bug, tho :+1:

**Comment by muckSponge** [comment]
Dup of #223 but I've referenced it in #223 because the videos show the problem well. I'll see if I can fix this now, as I've managed to reproduce the problem.
