### ISSUE TITLE
Synced account address broken in hamburger (three dot) menu

### ISSUE THREAD

**Issue by KhushrajRathod** [muckSponge/MaterialFox#239]
**Sanity checks (must complete)**
- [x] I have read and followed the installation instructions in the README
- [x] I have not modified the userChrome.css file
- [x] I have tested the latest release for my Firefox version, or commit on master/beta branch (beta is for Firefox Beta only) **Note that I'm using Firefox Developer Edition**

**Describe the bug**
_First of all I'd like to thank you for making such an amazing project._  
Bug:
1. Synced account name isn't completely displayed
2. "Sign in to sync" is shown (in menu bar) even when I'm already syncing. Clicking it does nothing

**To Reproduce**
1. Enable sync
2. Enable MaterialFox
3. Click on Three-dot menu
4. Sync account name is only half shown ----- (1)
5. Click the account name
7. 'Sign in to sync' is still shown ----- (2)

**Screenshots**
**Problem 1:**
![Screenshot 2020-07-31 at 5 40 14 PM](https://user-images.githubusercontent.com/44947946/89033900-5f0b9000-d327-11ea-9546-bc60512a4f8e.png)

**Problem 2:**
![Screenshot 2020-07-31 at 5 44 46 PM](https://user-images.githubusercontent.com/44947946/89033952-7cd8f500-d327-11ea-972a-bd8a18e3e669.png)

**I'm already syncing:**
![Screenshot 2020-07-31 at 5 45 38 PM](https://user-images.githubusercontent.com/44947946/89034005-9a0dc380-d327-11ea-851e-582d336a3e59.png)

**System info**
 - OS: macOS 10.15.6
 - Firefox version: 80.0b2

**Comment by KhushrajRathod** [comment]
Okay so both issues fixed themselves, idk how...

**Comment by KhushrajRathod** [comment]
The issue is back. This seems weird

**Comment by muckSponge** [comment]
Are you sure this is a MaterialFox issue? Have you tried with the default theme? I can't reproduce on my end.

**Comment by KhushrajRathod** [comment]
> Are you sure this is a MaterialFox issue? Have you tried with the default theme? I can't reproduce on my end.

Ok so this seems like a Firefox Issue... I've noticed that in the first window opened, the synced address is okay, the second window it breaks. Closed as reproducible without MaterialFox

**Comment by KhushrajRathod** [comment]
Fixed in 80.0b4
