### ISSUE TITLE
Search engine Icon missing in URL bar

### ISSUE THREAD

**Issue by KhushrajRathod** [muckSponge/MaterialFox#240]
**Sanity checks (must complete)**
- [x] I have read and followed the installation instructions in the README
- [x] I have not modified the userChrome.css file
- [x] I have tested the latest release for my Firefox version, or commit on master/beta branch (beta is for Firefox Beta only)  
**Note that I'm using Firefox Developer Edition**

**Describe the bug**
The search engine icon in the URL bar is missing

**To Reproduce**
1. Enable MaterialFox

**Screenshots**
Firefox:
![Screenshot 2020-07-31 at 8 05 30 PM](https://user-images.githubusercontent.com/44947946/89045469-1a89ef80-d33b-11ea-92f0-733063656e32.png)

Chrome:
![Screenshot 2020-07-31 at 8 03 49 PM](https://user-images.githubusercontent.com/44947946/89045329-de568f00-d33a-11ea-8563-f3166b6a21b2.png)

**System info**
 - OS: macOS 10.15.6
 - Firefox version: 80.0b2

**Comment by muckSponge** [comment]
I'm unable to reproduce this in 80.0b2. Tried default, light, dark themes, high DPI, low DPI. The search icon is present in all configurations. Does it happen with a fresh profile?

**Comment by KhushrajRathod** [comment]
Ok, so this might be my fault, but I just realized that this issue only occurs when I have an extension controlling my new tab page (I use tabbliss). The issue occurs because when you use an extension, "Extension (<Name>)" is present instead of the icon. When I type something, the "Extension (Tabbliss)" is gone and there's no search icon.

![ezgif-2-033b8f329495](https://user-images.githubusercontent.com/44947946/89115083-5f18a680-d473-11ea-84ff-8f02d4906e02.gif)

- Why this matters to me
When using container tabs for the search engine, if you search for something, the new tab page remains and a new tab is opened for the search results (in the container). This leaves the new tab page to be reused and hence I can notice the absence of the Search Icon

**Comment by muckSponge** [comment]
Ok, got it. I'll see if I can fix this.

**Comment by KhushrajRathod** [comment]
Great, thanks 👍

**Comment by muckSponge** [comment]
Should be fixed now. Definitely was a bug due to me ignoring the invalid proxy state of the urlbar when in an extension page (basically it is invalid if what is entered in the urlbar does not match the URL of the page). Now it only hides the icon if the proxy state is valid and it seems to work.

**Comment by KhushrajRathod** [comment]
> Should be fixed now. Definitely was a bug due to me ignoring the invalid proxy state of the urlbar when in an extension page (basically it is invalid if what is entered in the urlbar does not match the URL of the page). Now it only hides the icon if the proxy state is valid and it seems to work.

Nice, it works
