### ISSUE TITLE
Drop-downs (Or should I say, drop ups) broken inside customize menu

### ISSUE THREAD

**Issue by KhushrajRathod** [muckSponge/MaterialFox#241]
**Sanity checks (must complete)**
- [x] I have read and followed the installation instructions in the README
- [x] I have not modified the userChrome.css file
- [x] I have tested the latest release for my Firefox version, or commit on master/beta branch (beta is for Firefox Beta only)  
**Note that I'm using Firefox Developer Edition**

**Describe the bug**
The drop-downs in the customize menu (For theme and density) don't have enough padding on their sides, and they hover color overflows

**To Reproduce**
1. Enable MaterialFox
2. Three dots ---> Customize
3. Click themes or density

**Screenshots**
(GIF)

![Screen Recording 2020-07-31 at 8 06 59 PM](https://user-images.githubusercontent.com/44947946/89046131-19a58d80-d33c-11ea-9a2e-25dd06b881df.gif)

**System info**
 - OS: macOS 10.15.6
 - Firefox version: 80.0b2

**Comment by muckSponge** [comment]
Should be fixed now. Code is getting more and more hacky for dropdowns, menupopups, panels, etc. because Mozilla keep migrating them to shadow DOM and this is makes some parts virtually untouchable from userChrome.css.

**Comment by KhushrajRathod** [comment]
Hi, I'm using the beta branch, could you include that fix there too?

**Comment by KhushrajRathod** [comment]
Can confirm it works, fixed.
