### ISSUE TITLE
How to get black background with white tabs as seen in README?

### ISSUE THREAD

**Issue by KhushrajRathod** [muckSponge/MaterialFox#244]
![Screenshot 2020-08-01 at 12 49 27 PM](https://user-images.githubusercontent.com/44947946/89096608-6edab100-d3c7-11ea-88a7-62db06ebbc76.png)

How do you get a black background with white tabs as seen in README?
I'm using macOS 10.15.6, and setting theme to default gives me the light theme.

**Comment by adamrobertt** [comment]
The theme turns dark when your system is in dark mode. If you're on "default" or "auto" during the day, you'll have to manually toggle dark mode on.

**Comment by KhushrajRathod** [comment]
> The theme turns dark when your system is in dark mode. If you're on "default" or "auto" during the day, you'll have to manually toggle dark mode on.

Ah no, I'm not talking about the complete dark theme, I'm talking about the dark theme with white tabs

![Screenshot 2020-08-01 at 12 49 27 PM](https://user-images.githubusercontent.com/44947946/89103713-61431c80-d403-11ea-8888-30a412dfb13a.png)

Turning on system dark mode while using the "default" theme gives the equivalent of the dark theme

**Comment by muckSponge** [comment]
That was the default theme in Firefox. It's been a while but I think at some point I decided to check for default theme or light theme and override the CSS colours to match Chrome's light theme, and same for the dark theme and private browsing mode. The default theme originally had some overrides as well but I think this became too difficult to maintain and usually when people install this theme they expect it to look like Chrome (light or dark).

You can get this look pretty much exactly by using something like Firefox Color. MaterialFox will detect that you're using a custom theme and won't override the colours.

I still need to update the screenshot in the README to take out that middle image.

**Comment by KhushrajRathod** [comment]
> That was the default theme in Firefox. It's been a while but I think at some point I decided to check for default theme or light theme and override the CSS colours to match Chrome's light theme, and same for the dark theme and private browsing mode. The default theme originally had some overrides as well but I think this became too difficult to maintain and usually when people install this theme they expect it to look like Chrome (light or dark).
> 
> You can get this look pretty much exactly by using something like Firefox Color. MaterialFox will detect that you're using a custom theme and won't override the colours.
> 
> I still need to update the screenshot in the README to take out that middle image.

Oh okay thank you! I was partially worried you're not active on GitHub and this project would die... This project will remain maintained right?

**Comment by muckSponge** [comment]
> Oh okay thank you! I was partially worried you're not active on GitHub and this project would die... This project will remain maintained right?
That's the plan. It does get harder to maintain as time goes on. Every Firefox update breaks things and more code must be added to fix them. You end up with quite a lot of old code which no longer does anything. Might need to do some "spring cleaning" and simplify the codebase at some point. I've been putting a few things off because of this but the intention is to fix most of these bugs.

**Comment by KhushrajRathod** [comment]
> > Oh okay thank you! I was partially worried you're not active on GitHub and this project would die... This project will remain maintained right?
> 
> That's the plan. It does get harder to maintain as time goes on. Every Firefox update breaks things and more code must be added to fix them. You end up with quite a lot of old code which no longer does anything. Might need to do some "spring cleaning" and simplify the codebase at some point. I've been putting a few things off because of this but the intention is to fix most of these bugs.

Nice. Thanks!
