### ISSUE TITLE
Enlarged navigation and new tab buttons

### ISSUE THREAD

**Issue by shscs911** [muckSponge/MaterialFox#245]
**Sanity checks (must complete)**
- [x] I have read and followed the installation instructions in the README
- [x] I have not modified the userChrome.css file
- [x] I have tested the latest release for my Firefox version, or commit on master/beta branch (beta is for Firefox Beta only)

**Describe the bug**
  After the latest MaterialFox update, the navigation arrows, Home button and New Tab button have become enlarged and looks out of place with the rest of the UI. I don't know if the issue is with the latest release, as I recently updated both Firefox and MaterialFox after a long time.

**To Reproduce**
1. Open Firefox
2. Navigation buttons are magnified

**Screenshots**
![firefox-change](https://user-images.githubusercontent.com/44034402/89180814-27fbdf80-d5b0-11ea-9635-e94bc6a22e67.png)
Enlarged buttons after last update
OS: Windows 10
Firefox: Firefox Developer Edition 80.0b3 (64-bit)
MaterialFox: Current `master` branch

----

![firefox-original](https://user-images.githubusercontent.com/44034402/89181036-7f01b480-d5b0-11ea-98e6-0e3fb6b92b1f.png)
Normal button layout
OS: Arch Linux
DE: KDE Plasma 5.19.4
Firefox: Firefox Developer Edition 75.0b11 (64-bit)
MaterialFox: v72.0

I'm using screenshots from my Linux version of Firefox as it was identical to the Windows one before the update.

**Comment by muckSponge** [comment]
I think you have touch density enabled under Customize -> Density. If you set it to normal density it should look like the bottom screenshot. Really I should support touch density but I've hard-coded quite a few bits and pieces which makes it difficult.

**Comment by shscs911** [comment]
Thanks a lot, mate. It worked. Now the icons are back to normal. I'm guessing this is something Windows-specific? I don't actually remember setting the Density as touch. Thanks again for the amazing theme.

**Comment by muckSponge** [comment]
If you have a touch screen laptop or tablet it might default to the touch density setting. Glad you like it, thanks for using it!
