### ISSUE TITLE
Extension alignment issue on bookmark toolbar

### ISSUE THREAD

**Issue by Bulogan** [muckSponge/MaterialFox#247]
**Sanity checks (must complete)**
- [x] I have read and followed the installation instructions in the README
- [x] I have not modified the userChrome.css file
- [x] I have tested the latest release for my Firefox version, or commit on master/beta branch (beta is for Firefox Beta only)

**Describe the bug**
When adding an extension in bookmarks toolbar, the extension is misaligned compared to native buttons from firefox.

**To Reproduce**
1. Enable 'Bookmarks Toolbar'
2. Customize
3. Add extension into toolbar 
4. Notice that its misaligned.

**Screenshots**
![Annotation 2020-08-05 235700](https://user-images.githubusercontent.com/69257763/89440514-4dd6df00-d77e-11ea-9a97-4ad8dc958eb6.jpg)
red line is for reference.

**System info**
 - OS: Windows 10
 - Firefox version: v79

**Comment by muckSponge** [comment]
Should be resolved now.
