### ISSUE TITLE
Tab selection is not displayed

### ISSUE THREAD

**Issue by Madis0** [muckSponge/MaterialFox#25]
Tab selection is a new feature in Firefox 63 (should be partly available in 62 by enabling `browser.tabs.multiselect`) and this theme does not seem to highlight the selected tabs in any way. Chrome has had this feature for a long time, so it's not hard to guess what they should look like :P

Tested on Firefox 63.0b6, macOS 10.13.6.

**Comment by muckSponge** [comment]
Multiselected tabs are now styled, though because they are semi-transparent you will be able to see the overlap between them. That's another issue though.
