### ISSUE TITLE
[Question] Does the white/black theme exist?

### ISSUE THREAD

**Issue by ovasquez** [muckSponge/MaterialFox#250]
First of all, thanks for the amazing Firefox theme!

Is there a way to achieve the style this screenshot? (taken from the MaterialFox image)
I tried using the default, light and dark theme, but it doesn't look like this with white selected tab and dark background, and I also didn't see anything about this in the rest of the instructions.

![image](https://user-images.githubusercontent.com/7527242/89844483-f0a1ab80-db38-11ea-8315-ae45d0671465.png)

_PS: the "bug" label was added automatically and I can't remove it._

**Comment by muckSponge** [comment]
Originally, this theme used the default theme colours, but this required coordinating two themes - a userChrome.css one and a conventional theme/add-on to get the material colours while maintaining theme support. Now, the colours are forced for the light, dark, and default themes (other themes still work). This means default now resembles white.

You can use something like Firefox Color to apply any kind of colour you want. I'd start there. You might need to change the colour very slightly so it doesn't trigger the forced theme override (MaterialFox checks certain colours in the theme to see if it should override it).

**Comment by KhushrajRathod** [comment]
https://github.com/muckSponge/MaterialFox/issues/244

**Comment by ovasquez** [comment]
Thanks for the answer, I'll give it a try with Firefox Color.
