### ISSUE TITLE
Is it possible to public this project to firefox addon store?

### ISSUE THREAD

**Issue by zq1997** [muckSponge/MaterialFox#253]
This is a very nice project with wonderful UI experience, but it has a difficult installation/update process.

Is it possible to publish this project to firefox addon store? After install the addon, it detect the firefox version automatically, download files from github automatically and write it to local directory.

**Comment by muckSponge** [comment]
It's a nice thought but unfortunately I don't think Firefox add-ons are allowed direct access to the file system so any kind of automated installation would need to happen via an executable which is outside of the scope of this userChrome theme for now.

**Comment by zq1997** [comment]
Yeah, intuitively I also thought it's impossible to write local file only via add-on out of security consideration.

However, it seems that firefox add-on is privileged (I am not very sure), considering the following articles?

![OS.File_for_workers](https://developer.mozilla.org/zh-CN/docs/Mozilla/JavaScript_code_modules/OSFile.jsm/OS.File_for_workers)

**Comment by muckSponge** [comment]
Old extensions used to be privileged but Mozilla moved to a sandboxed add-on environment with [heavy restrictions](https://wiki.mozilla.org/WebExtensions/Filesystem).
