### ISSUE TITLE
Secure lock icon is a bit different from chrome's

### ISSUE THREAD

**Issue by bogdanbryzh-official** [muckSponge/MaterialFox#257]
**Screenshots**
This is how it looks in firefox
![Screenshot from 2020-09-03 19-56-58](https://user-images.githubusercontent.com/66746788/92145224-9090e300-ee20-11ea-820a-ff2bd1647bf1.png)
chrome/chromium
![Screenshot from 2020-09-03 19-57-21](https://user-images.githubusercontent.com/66746788/92145225-91c21000-ee20-11ea-8245-41350e7f2f50.png)

**System info**
 - OS: Arch Linux
 - Firefox version: 80.0.1

**Note**
It will be very cool if you'll tell me how to fix it. So i'll learn smth new))

**Comment by muckSponge** [comment]
Should have been fixed in 45763ac. Sorry I can't give direct instructions, it took a lot of fiddling for various edge cases. I will close this, if the fix doesn't work put a comment in #272.
