### ISSUE TITLE
[bug] icons' color didn't change when changed to dark mode

### ISSUE THREAD

**Issue by alanlai1234** [muckSponge/MaterialFox#258]
**Sanity checks (must complete)**
- [x] I have read and followed the installation instructions in the README
- [x] I have not modified the userChrome.css file
- [x] I have tested the latest release for my Firefox version, or commit on master/beta branch (beta is for Firefox Beta only)

description:
this looks like a bug, the icons don't change its color to white when in dark mode, which is unclear.

screenshot:
<img width="1440" alt="截圖 2020-09-05 下午1 56 46" src="https://user-images.githubusercontent.com/45114742/92298912-49b9ff00-ef80-11ea-844c-83679d0aa90f.png">

reproduce:
change to dark mode in firefox

os : macos catanila
newest firefox

**Comment by KhushrajRathod** [comment]
It seems like you haven't copied the user.js file to your profiles folder

**Comment by alanlai1234** [comment]
Oh really! so sorry for the mistake!

**Comment by KhushrajRathod** [comment]
> Oh really! so sorry for the mistake!

Glad it helped! @muckSponge Please close
