### ISSUE TITLE
White boxes near edges of active tab when using Firefox Alpenglow

### ISSUE THREAD

**Issue by khrj** [muckSponge/MaterialFox#259]
**Sanity checks (must complete)**
- [x] I have read and followed the installation instructions in the README
- [x] I have not modified the userChrome.css file
- [x] I have tested the latest release for my Firefox version, or commit on master/beta branch (beta is for Firefox Beta only) **Note that I'm using Firefox Developer Edition**

**Describe the bug**
White squares are seen at both ends of the active tab when using the new Firefox Alpenglow theme

**To Reproduce**
1. Go to Customize > Themes > Firefox Alpenglow

**Screenshots**
![Screenshot 2020-09-08 at 8 49 29 PM](https://user-images.githubusercontent.com/44947946/92496222-64da7800-f1e7-11ea-833e-629618b50991.png)

**System info**
 - OS: macOS 10.15.6
 - Firefox version: 81.0b7

**Additional context**
This probably occurs with other low-contrast themes as well

**Comment by mthuc** [comment]
Seen with most themes (using MaterialFox Helper extension  as well).
Firefox 81 stable release.

**Comment by redfoxseattle** [comment]
I have this same issue and never was able to really resolve it until recently. This isn't a complete fix, but I found out that if I set the MaterialFox Helper to Default, and then created or imported a theme using the new [Firefox Color tool](https://color.firefox.com/?fromAddon=true), every color combination I picked worked. So if I found a theme I really liked, I just screengrabbed it and found all of the colors and then created a theme and saved it - no more squares.

**Comment by mthuc** [comment]
> 
> 
> I have this same issue and never was able to really resolve it until recently. This isn't a complete fix, but I found out that if I set the MaterialFox Helper to Default, and then created or imported a theme using the new [Firefox Color tool](https://color.firefox.com/?fromAddon=true), every color combination I picked worked. So if I found a theme I really liked, I just screengrabbed it and found all of the colors and then created a theme and saved it - no more squares.

Thanks! Will try this!

**Comment by muckSponge** [comment]
This is probably only an issue for themes with (semi)transparent toolbar backgrounds, which would explain why you don't see the problem when you create the theme with Firefox Color (it doesn't use transparent colours AFAIK).

Might be possible to clip out the bottom left and right corners of the tab with CSS but it's not a simple one-liner fix. The issue stems from the way the rounded bottom corners of the tab is created. It's actually two invisible circles on the bottom left and right with a border the same colour as the tab. If the tab is semi-transparent, the overlap of the border and the actual tab causes transparency to be reduced.

When I have time I'll see if I can come up with a fix but a workaround is to just pick themes which don't have a transparent tab or toolbar.
