### ISSUE TITLE
Extension page text broken

### ISSUE THREAD

**Issue by foreverxml** [muckSponge/MaterialFox#261]
**Sanity checks (must complete)**
- [x]  I have read and followed the installation instructions in the README
- [x] I have not modified the userChrome.css file
- [x] I have tested the latest release for my Firefox version, or commit on master/beta branch (beta is for Firefox Beta only)

**Describe the bug**
When on extension page, the extension name (e.g. Extension (Tabliss) ) is slightly lower than center

**To Reproduce**
1. Enable any extension (uBlock Origin, Tabliss...)
2. Go to an extension page (Tabliss Tab, uBlock Control Panel)
4. See issue

![image](https://user-images.githubusercontent.com/52264162/92791299-caef0880-f369-11ea-89e4-e896d341ce57.png)
![image](https://user-images.githubusercontent.com/52264162/92791387-db9f7e80-f369-11ea-9e30-a7e46a025177.png)
![image](https://user-images.githubusercontent.com/52264162/92791467-ef4ae500-f369-11ea-8907-bda7880d86de.png)

**System info**
 - OS: Win10
 - Firefox version: 80.0.1 64 bit

**Comment by muckSponge** [comment]
Should be fixed in 45763ac.
