### ISSUE TITLE
Make Firefox look like Edge (Chromium)

### ISSUE THREAD

**Issue by chad-abizeid** [muckSponge/MaterialFox#270]
Anyone know how to make Firefox look like Edge browser, Chromium version? I got it to look like regular Chrome using your patch: https://github.com/muckSponge/MaterialFox

However, I prefer Edge's style. Any ideas? I would've switched to Edge as my primary browser but there's no extension or trick I'm aware of to do the below:

1. Open urlbar links in new tabs automatically
2. Open favorites in new tabs automatically

I don't care to do the middle click mouse button method. Plus, Edge favorites bar is clumsy and stupid.

**Comment by fmeyertoens** [comment]
This theme follows Material Design while Edge follows Fluent UI. Such a request is therefore probably beyond the scope of this project but you can easily use this project as a starting point.
You might find your answer here: [https://www.reddit.com/r/FirefoxCSS/comments/hhh635/any_theme_similar_to_chromium_edge/](https://www.reddit.com/r/FirefoxCSS/comments/hhh635/any_theme_similar_to_chromium_edge/)

**Comment by chad-abizeid** [comment]
Thanks for the info. I'll give it a shot.
