### ISSUE TITLE
[Feature] Change urlbar font size

### ISSUE THREAD

**Issue by issadarkthing** [muckSponge/MaterialFox#274]
**Sanity checks (must complete)**
- [x] I have read and followed the installation instructions in the README
- [x] I have not modified the userChrome.css file
- [x] I have tested the latest release for my Firefox version, or commit on master/beta branch (beta is for Firefox Beta only)

**Screenshots**
![image](https://user-images.githubusercontent.com/50593529/104113118-76689380-5331-11eb-9d66-a8ca65252cd1.png)

**System info**
 - OS: Artix Linux 5.10.4 (64 bit)
 - Firefox version: 84.0.1 (64 bit)

**Additional context**
The font size inside the url bar is too small. I wanted to change it manually but I'm afraid that it'll break other components such as url bar height. It would be awesome if we can manually choose the font size from the `chrome/variables.css` file.

**Comment by ianpan870102** [comment]
@muckSponge @DIHONKSON Thanks for adding the field font size variable in commit 0eff520. However, that line should actually be added under the :root section, otherwise it will only impact the light theme, and NOT the dark theme.
