### ISSUE TITLE
Internal pages omit product name

### ISSUE THREAD

**Issue by Madis0** [muckSponge/MaterialFox#28]
In Chromium, any internal `chrome://` pages - like settings, bookmarks, extensions - have a "Chromium" title in the address bar, along with the product icon. Firefox also has this style for everything that starts with `about:`
Why does this userstyle hide the title then? Or even if intended, a preference would make sense.

Firefox 63.0b8, style build b0002274c55e25484d794999e256a6ea8ea0b61f.

**Comment by muckSponge** [comment]
Should have been fixed in 1ba2429685e81811d8d3c38d283a1c0e5c0edf07.

**Comment by Madis0** [comment]
Confirmed fixed.
