### ISSUE TITLE
Grey boxes within hover effects to the left of the URL bar after updating to Firefox Beta 87.0b4 (64-bit) version

### ISSUE THREAD

**Issue by HorusOwl** [muckSponge/MaterialFox#280]
These only appear on hover.
![momentum](https://user-images.githubusercontent.com/65387181/109750307-eefc1a00-7c27-11eb-962d-615e73ba243f.png)
![permissions](https://user-images.githubusercontent.com/65387181/109750310-ef94b080-7c27-11eb-8e42-02cd837f72ab.png)
![lock](https://user-images.githubusercontent.com/65387181/109750311-f02d4700-7c27-11eb-90e0-b4ca4eae4598.png)

**Comment by muckSponge** [comment]
Should be resolved now.

**Comment by HorusOwl** [comment]
👍 the text is a bit smaller but it's no big deal
