### ISSUE TITLE
Change font size of text on URL Bar

### ISSUE THREAD

**Issue by MeisterJames** [muckSponge/MaterialFox#287]
Hello, would it be possible to change the font and font size of the URL Bar? For some reason mine looks very mono-chrome and a small size. Here's an example of my Firefox vs my Chrome

![image](https://user-images.githubusercontent.com/46969223/113456380-27377980-93db-11eb-92c6-5281f03e5775.png)
![image](https://user-images.githubusercontent.com/46969223/113456515-6796f780-93db-11eb-9aa9-c029fcb54904.png)

**Comment by Biodegradavide** [comment]
I'm having the same issue. What do you mean with "adding to :root"? Thanks

**Comment by ianpan870102** [comment]
@Biodegradavide The current line `--toolbar-field-fontsize: 14px !important;` is only present in the light mode part of the code. If you want the font size set for both light and dark modes, you should set it in the :root section (which should be somewhere around Line 118-130 in variable.css)
