### ISSUE TITLE
Tab does not display properly when using on Nightly 89.0a1 

### ISSUE THREAD

**Issue by Fourthbus** [muckSponge/MaterialFox#288]
**Sanity checks (must complete)**
- [1] I have read and followed the installation instructions in the README
- [1] I have not modified the userChrome.css file
- [1] I have tested the latest release for my Firefox version, or commit on master/beta branch (beta is for Firefox Beta only)

**Describe the bug**
MaterialFox is disintegrated... (see screenshot)

**To Reproduce**
1. Install MaterialFox on this version of FireFox.
2. Problem

**Screenshots**
<img width="714" alt="image" src="https://user-images.githubusercontent.com/13725288/114057277-555d0380-988a-11eb-82fb-0db4f302d663.png">

**System info**
 - OS: Mac OS 10.15.7
 - Firefox version: 89.0a1 Nightly (2021-04-08) (64-bit Mac)

**Comment by troysjanda** [comment]
Due to the new Proton UI. It looks like the Proton UI will break some of Materialfox CSS and will need to be updated once the Proton UI is fully released and enabled by default post FF89
