### ISSUE TITLE
Tab design is not the same as chrome

### ISSUE THREAD

**Issue by neerajklite** [muckSponge/MaterialFox#293]
The tab design is changed in the latest version. The side edges does not have the curve and fall straight. They also seem shorter in height . Firefox stable 88.0.1
![Screenshot 2021-05-12 at 11 19 35 AM](https://user-images.githubusercontent.com/53794487/117925191-8199f300-b314-11eb-975e-ee6282efa646.png)

**Comment by muckSponge** [comment]
I've switched the master branch to tackle Firefox 89 support which includes Mozilla's proton redesign by default. There's a [release v88.0](https://github.com/muckSponge/MaterialFox/releases/tag/v88.0) you can use which should still work fine for pre-proton, or you can [enable the proton redesign in Firefox 88](https://www.makeuseof.com/how-to-enable-new-firefox-proton-design-now/) and keep using the latest master commits.

**Comment by neerajklite** [comment]
That worked. Also great to know work is already being put for the upcoming proton designs. Thank you for your work. Proton is way forward and makes Firefox better. But in a lot of ways still lags behind chrome, like even font treatment in the UI is horrible to say the least

**Comment by sheeepdev** [comment]
This is fixed for the new firefox too!
