### ISSUE TITLE
Search history entries and Right-click context menu entries not highlighted when hovering over them

### ISSUE THREAD

**Issue by shscs911** [muckSponge/MaterialFox#295]
**Sanity checks (must complete)**
- [x] I have read and followed the installation instructions in the README
- [x] I have not modified the userChrome.css file
- [x] I have tested the latest release for my Firefox version, or commit on master/beta branch (beta is for Firefox Beta only)

**Describe the bug**
Search history entries and Right-click context menu entries not highlighted when hovering over them.

**To Reproduce**

##### Search History Entries
1. Open any search form
2. Press down/up
3. Hover over the entries
4. Entries are not highlighted

##### Right-click Context Menu Entries
1. Right-click on any webpage
2. Hover over the entries
3. Entries are not highlighted

**Additional Info**
- Possibly related to #286. Not sure if search history entries are following the same scheme as context-menu entries.

**Screenshots**
##### Search History
![Search History 02](https://user-images.githubusercontent.com/44034402/119316142-38428f80-bc94-11eb-8a17-24c379ed8083.png)
![Search History 01](https://user-images.githubusercontent.com/44034402/119316148-3a0c5300-bc94-11eb-88e9-2e011592345d.png)

##### Right-click
![Right-click 02](https://user-images.githubusercontent.com/44034402/119316176-44c6e800-bc94-11eb-8dd0-947120b85dca.png)
![Right-click 01](https://user-images.githubusercontent.com/44034402/119316181-47294200-bc94-11eb-901d-8deea1560ce5.png)

**System info**
 - OS: Arch Linux
 - Firefox version: 88.0b9

**Comment by ThatIsAPseudo** [comment]
Same issue on macOS with Firefox 88.0.1

**Comment by TheAresjej** [comment]
## temporary solution:
Go to **about:config** > search for **layout.css.color-mix.enabled** > set to **true**

**Comment by shscs911** [comment]
Thanks a lot. That worked. I somehow missed the solution when I read the related issue.
