### ISSUE TITLE
Tabs in FF89 have shadows . Thats not present in chrome and totally unnecessary.

### ISSUE THREAD

**Issue by neerajklite** [muckSponge/MaterialFox#297]
![Screenshot 2021-06-02 at 9 39 06 AM](https://user-images.githubusercontent.com/53794487/120422724-80de0500-c386-11eb-938a-7e642dcbbf92.png)

**Comment by Artanisky** [comment]
In the tabbar.css file for the .tab-background class, add `box-shadow: none! Important;`
