### ISSUE TITLE
FF89 dark theme tab contrast is insufficient.

### ISSUE THREAD

**Issue by neerajklite** [muckSponge/MaterialFox#299]
![Screenshot 2021-06-02 at 9 43 23 AM](https://user-images.githubusercontent.com/53794487/120422956-12e60d80-c387-11eb-8287-fc8fa6682885.png)

**Comment by muckSponge** [comment]
This has been fixed recently:
<img width="530" alt="image" src="https://user-images.githubusercontent.com/5405629/128670435-5c6c5acc-8dc4-4539-931b-53d25550e21b.png">
