### ISSUE TITLE
Make HTTPS and HTTPS + EV SSL always use the same color

### ISSUE THREAD

**Issue by Madis0** [muckSponge/MaterialFox#31]
If you provide a preference - quoting the readme:

> Replicate Chrome identity colours (or lack thereof):
> 
>  *   [about:config] Add new entry `materialFox.disableIdentityColors` with value `true`.
>   *  Restart Firefox.

then please make the green locks/texts consistently gray or consistently green on all pages with HTTPS.

Pages with EV SSL are not more secure than those without, this has been [proven](https://scotthelme.co.uk/are-ev-certificates-worth-the-paper-theyre-written-on/) [many](https://www.troyhunt.com/on-the-perceived-value-ev-certs-cas-phishing-lets-encrypt/) [times](https://stripe.ian.sh/) by leading security experts, even Google knows that ([so they have an experiment for hiding the text](https://twitter.com/scott_helme/status/989841573235122177)).

My personal opinion is that you should just keep it gray like Chrome and therefore remove the redundancy of a preference/green text code. (Hence my initial confusion at #24)

**Comment by muckSponge** [comment]
Tested latest commit and it should be resolved. If not, please feel free to re-open.
