### ISSUE TITLE
Address bar totally broken on any dark theme

### ISSUE THREAD

**Issue by hrqmonteiro** [muckSponge/MaterialFox#323]
**Sanity checks (must complete)**
- [X ] I have read and followed the installation instructions in the README
- [X ] I have not modified the userChrome.css file
- [X ] I have tested the latest release for my Firefox version, or commit on master/beta branch (beta is for Firefox Beta only)

**Describe the bug**
My dude, just copied the files to my Firefox and got this.
The toolbar is complete white (background and foreground color)

**To Reproduce**
I said above.

**Screenshots**
On system auto theme:
![Screenshot from 2022-07-17 11-45-25](https://user-images.githubusercontent.com/17055027/179403717-41092186-9244-4e0a-913f-a705b9824fc5.png)

On forced firefox dark theme:
![Screenshot from 2022-07-17 11-45-38](https://user-images.githubusercontent.com/17055027/179403830-b70f7223-6c60-4ded-aad2-e1e4844c959a.png)

Only works ok with light theme:
![Screenshot from 2022-07-17 11-46-07](https://user-images.githubusercontent.com/17055027/179403836-216fada0-a233-4830-bef9-aa703d7fe9d2.png)

It's fine on light theme only.

**System info**
 - OS: Ubuntu 22.04
 - Firefox version: 102.0.1

**Comment by dragonDScript** [comment]
I'm also reproducing this on Windows 11 on the dark theme.

**Comment by sikaiser** [comment]
This is the same as #317, there is already a pull request ( #322 ) for it.

**Comment by dragonDScript** [comment]
Thanks

**Comment by MarcAhoy** [comment]
@dragonDScript yup, that work's for me
