### ISSUE TITLE
Dark context menus

### ISSUE THREAD

**Issue by scorthyn** [muckSponge/MaterialFox#36]
Is it possible to have dark context menus? (favorites, etc)

Wonderful theme! thanks so much!

**Comment by muckSponge** [comment]
It's doable but not implemented yet. Marked as enhancement and I'll get to it once I've implement styled context menus / popups.

**Comment by muckSponge** [comment]
This is pretty much done now so I'll close the issue. If you experience specifically dark-related problems I can re-open it.
