### ISSUE TITLE
Tab Bar Flickers on Swipe (OSX)

### ISSUE THREAD

**Issue by Trystanr** [muckSponge/MaterialFox#37]
The tab bar has a blue tint while swiping with OSX between fullscreen apps. 
On swipe finish, the tab bar flickers black then back to the theme.

**Comment by muckSponge** [comment]
Should be fixed in windows-improvements branch. Expect this to be merged into master in a few days. If you're ok to switch branches, let me know how it goes.

**Comment by Trystanr** [comment]
Yeah, all good.

**Comment by muckSponge** [comment]
Merged fixes into master.
