### ISSUE TITLE
Chrome-style context menus

### ISSUE THREAD

**Issue by muckSponge** [muckSponge/MaterialFox#46]

**Comment by Madis0** [comment]
Potential inspiration: [this](https://github.com/Aris-t2/CustomCSSforFx/blob/master/classic/css/generalui/context_bfrsb_labels_with_icons.css) with [this](https://github.com/Aris-t2/CustomCSSforFx/blob/master/classic/css/generalui/context_bfrsb_labels_without_icons.css). Not sure about the license though, so I don't advise copying.

**Comment by RisingFireStar** [comment]
> 
> 
> _No description provided._

Well, you could make it like this.

![mozillachrome-context-menu](https://user-images.githubusercontent.com/23248936/46967971-c60c7600-d0ba-11e8-8e24-3557dc579b13.png)

**Comment by marcelharinck** [comment]
Very nice!

**Comment by muckSponge** [comment]
Free time is a rare commodity these days. Hopefully will have some time to get into this later this week.

**Comment by muckSponge** [comment]
<img width="253" alt="image" src="https://user-images.githubusercontent.com/5405629/51613003-b2ed2a00-1f76-11e9-98ab-90502c50e07e.png">
This is what I've got so far. Might experiment later with the more conventional icon placement but it will make the context menu significantly wider.

**Comment by muckSponge** [comment]
Merged changes into master branch. Subheadings are not styled yet so they will look pretty nasty.

**Comment by TowelBin** [comment]
I think that we should just implement context menus as they are now in chrome. all we would need is to remove the icons from menus, make backgrounds white, and change the hover color

**Comment by muckSponge** [comment]
I ended up going with a direct interpretation of the Material Menus spec for this one (except the Firefox-specific navigation buttons). This results in somewhat chunky menus but looks good IMO. I don't think we need to copy Chrome in every case, and we're already using non-OS panels and such in vanilla Firefox so this seems like a natural addition. Chrome is probably hampered by dev effort and compatibility considerations, otherwise I reckon they'd be doing something similar.
