### ISSUE TITLE
Incorrect bookmark toolbar nested folder arrows (macOS)

### ISSUE THREAD

**Issue by andrew-lozoya** [muckSponge/MaterialFox#55]
Been having weird issues with the arrows in the toolbar sub-folders... I've doubled check all the mandatory and required settings. Luckily this is the only issue I am facing since day one using this.

![Image of issue](https://i.ibb.co/hDFsrWw/2018-12-21-10-16-02.png)

**Comment by muckSponge** [comment]
I'm able to reproduce this on macOS only. Will have a look to see what code is causing this, probably just need a more specific CSS selector.
