### ISSUE TITLE
fyi,  just tried to send you some coffee and here's what happened

### ISSUE THREAD

**Issue by brenthueth** [muckSponge/MaterialFox#56]
#<img width="960" alt="image" src="https://user-images.githubusercontent.com/46110730/50544588-4de52500-0bc0-11e9-9a47-32d8cd340989.png">

thanks for the theme :) ... let me know if you fix your account at buymeacoffe.com (bhueth@gmail.com)

**Comment by muckSponge** [comment]
Very strange, I just tried it and it worked fine for me. The URL looks different though. Are you taken to https://www.buymeacoffee.com/n4ho5QX2l when you click it, or redirected elsewhere? I see your URL is https://www.buymeacoffee.com/thankyou/n4ho5QX2l. How did you get this URL; is this after you've clicked "Pay $x"?

Regardless, thanks for trying to show your support! Much appreciated.

**Comment by brenthueth** [comment]
Not sure what happened, but it worked this time :). Probably my goof.

Cheers



Brent

**Comment by muckSponge** [comment]
Thanks so much for the coffees, I really appreciate it!
