### ISSUE TITLE
UI bugs with overflowing tabs

### ISSUE THREAD

**Issue by Keith94** [muckSponge/MaterialFox#6]
### Left side
The overflow arrows are invisible, but there's a white line that overlaps the tab icons.

![firefox_2018-08-30_20-16-12](https://user-images.githubusercontent.com/5490615/44890944-a0a1e500-ac91-11e8-9492-442fa7f0e004.png)

### Right side
The "Simple New Tab" button clips behind the tab content when it's hovered or focused.

![image](https://user-images.githubusercontent.com/5490615/44890932-91bb3280-ac91-11e8-9689-0bbec5644c82.png)

**Comment by Keith94** [comment]
It's better if tabs can overflow, in my opinion, because managing lots of tabs becomes difficult otherwise.

**Comment by Keith94** [comment]
Hmm, it's hard to say. Prior to Firefox 57, they used a curved tabs design (+ overflow) without any "major" issues AFAIK. Could be some CSS tricks that make it work better.

Plus, over the years I've seen many complaints about Chrome's tab behavior (disappearing tab labels, etc.), but it's still your theme and your decision.

**Comment by muckSponge** [comment]
Resolved in eb51d014ad4ad0344090b4debfe4018bcc375e62. Decided not to disable overflow for now.

**Comment by Keith94** [comment]
Really good stuff!
