### ISSUE TITLE
White page flashing

### ISSUE THREAD

**Issue by Schanzation** [muckSponge/MaterialFox#63]
Hello! Is it possible to get this with MaterialFox?

https://9to5google.com/2019/01/18/google-chrome-fix-white-flash/

I don't want white flashing before loading a page. I tried ShadowFox and it completely fixed this problem but I want to be using MaterialFox. Tyty

I tried putting this inside the userChrome.css. It makes the website flash black. Its better than white but still quite annoying.

.browserContainer { background-color: #000000 !important; }

**Comment by muckSponge** [comment]
The white flash might possibly just be masked by the fact that ShadowFox themes web pages (not exactly sure, I tried the following and it didn't do anything):

```
#browser vbox#appcontent tabbrowser,
#content,
#tabbrowser-tabpanels,
browser[type=content-primary],
browser[type=content] > html {
  background: red /*var(--in-content-page-background)*/ !important;
}
```

Note, `--in-content-page-background` is a variable possibly set by the theme (not sure, haven't checked), so not available without the theme installed (hence I replaced it with red). It's taken from [ShadowFox](https://github.com/overdodactyl/ShadowFox/blob/master/css/userChrome-files/remove_white_flash.css).

I couldn't see any difference and never noticed any flashes before either. What website or scenario can this be reliably tested on?

**Comment by Schanzation** [comment]
I understand. I tried that code and its flashing red all the time. I changed it instead of red to #2a2a2e now and I prefer that over white atleast. Tyty
