### ISSUE TITLE
Firefox 65

### ISSUE THREAD

**Issue by Schanzation** [muckSponge/MaterialFox#64]
Hello! I just upgraded to Firefox 65 and I get two issues I can explain them better with a picture:

https://imgur.com/a/GKueOkW

I'm running Windows 10

**Comment by scorthyn** [comment]
I can confirm the empty corner space on new update, other than that its all good

**Comment by Schanzation** [comment]
Yes but for me on w10 the tab bar background color is way different than before I upgraded two hours ago

**Comment by muckSponge** [comment]
Does the default theme (without MaterialFox) have the same colour? If it's the same colour then I'm ok with that for now. I know Chrome's is a lot more washed out but it looks rather bland like that to me. If it's something you really think should be part of MaterialFox, feel free to make another issue for it and I might adapt the theme to match Chrome or add it as an option. The other issue should be fixed though in latest commit.

**Comment by Schanzation** [comment]
Did you find out how to change the background color?

**Comment by muckSponge** [comment]
```
#main-window
{
    background-image: linear-gradient(hsla(0, 0%, 70%, .8), hsla(0, 0%, 70%, .8)) !important;
}
```

Try something like that.

**Comment by Schanzation** [comment]
Before I had background color #202124

**Comment by muckSponge** [comment]
Glad you got it working how you like it :)
