### ISSUE TITLE
Missing scrollbar on drop down menu

### ISSUE THREAD

**Issue by Gigobitto** [muckSponge/MaterialFox#65]
Running 64.0.2, scrollbar doesnt exist in drop down menu (consequently mouse wheel doesnt work either)

**Comment by muckSponge** [comment]
Is there somewhere or somehow I can reproduce this behaviour where a scrollbar is required? Pretty much never see a drop down menu which requires scrolling, except for in the panel UI which does have a scrollbar for me.

**Comment by Gigobitto** [comment]
https://steamcommunity.com/stats/250900/leaderboards/1653528
![immagine](https://user-images.githubusercontent.com/23615575/51918286-89525980-23e1-11e9-9b2a-985730c2ea3e.png)

**Comment by muckSponge** [comment]
Should be fixed in latest commit.
