### ISSUE TITLE
white border around icons from menu  (regression)

### ISSUE THREAD

**Issue by heubergen** [muckSponge/MaterialFox#66]
<img width="197" alt="screen shot 2019-01-29 at 16 59 01" src="https://user-images.githubusercontent.com/5529410/51921192-311e5600-23e7-11e9-99f3-aef1bff0f490.png">
I don't think those white border around the icon should be displayed?

Was fine with 09dd974 (99% sure)

**Comment by muckSponge** [comment]
Should be fixed in latest commit. This is what happens when I make commits on master just before bed.

**Comment by muckSponge** [comment]
Will close this now but happy to re-open if the issue appears elsewhere.
