### ISSUE TITLE
Arrows in bookmark folder strcuture are not good visible

### ISSUE THREAD

**Issue by heubergen** [muckSponge/MaterialFox#67]
With Material Fox:
<img width="147" alt="screen shot 2019-01-29 at 17 01 58" src="https://user-images.githubusercontent.com/5529410/51921548-eb15c200-23e7-11e9-869e-cbed85e94d28.png">
Firefox Vanilla:
<img width="195" alt="screen shot 2019-01-29 at 17 02 46" src="https://user-images.githubusercontent.com/5529410/51921572-f5d05700-23e7-11e9-8312-2f388474e029.png">

Both time with default theme. Issue also appears with the dark theme (then the arrows are just too dark).

**Comment by muckSponge** [comment]
Should be resolved in cfe7650dbb17de4a1c5a809d5c82e5bcc649c81.

**Comment by muckSponge** [comment]
Closing this issue but happy to re-open if you spot this kind of problem elsewhere (it could potentially affect any `toolbarbutton` with something like a menu embedded in it, but I haven't found another example).
