### ISSUE TITLE
Suggestion: using releases

### ISSUE THREAD

**Issue by ovasquez** [muckSponge/MaterialFox#68]
Have you considered creating releases for the MaterialFox package?

You can add .zip or binary files after you create a release, that way people could got to that page and download a specific release, and a change-log could be inferred from the changes in each release.

**Comment by muckSponge** [comment]
That's a good idea. There are a few more issues I'd like to close first and then I'll look into releases.

**Comment by muckSponge** [comment]
I'm on it!
