### ISSUE TITLE
Close button is wrongly displayed for background tabs

### ISSUE THREAD

**Issue by Keith94** [muckSponge/MaterialFox#7]
### With your theme
Notice the close button element is still present, causing the tab text to fade prematurely.

![firefox_2018-08-30_20-31-23](https://user-images.githubusercontent.com/5490615/44891382-cfb95600-ac93-11e8-9006-a9130364718c.png)

### With button removed
It should only be displayed on hover/select (or whatever matches the default behavior).

![firefox_2018-08-30_20-31-44](https://user-images.githubusercontent.com/5490615/44891402-f5def600-ac93-11e8-99af-5893cf21719d.png)

**Comment by muckSponge** [comment]
I'd like to keep the close button fade in/out transition so we might need to add a ```width``` transition too, or a negative ```left-margin```. Will do some experimentation tonight to see what I can come up with.

**Comment by Keith94** [comment]
Couldn't you add the transition on the `display` or `visibility` CSS rules? Not sure, so I leave it up to you.

**Comment by muckSponge** [comment]
I've got a big commit in the works which will drastically change the tab close button behaviour to better match the latest Chrome dev builds.

The buttons will soon be present on background tabs all the time, but they won't clip as much of the tab text and will collapse when the tabs overflow. This is similar to Chrome's behaviour except in Chrome, the close buttons collapse when the tabs reach a certain width. Unfortunately there isn't a CSS-only mechanism for this so I've done my best to compromise.

If I close this issue but you're not satisfied with the outcome, feel free to open another issue and I'll have another crack at conserving the tab text.

**Comment by muckSponge** [comment]
Pushed 1ab209982a245ef8dca4bd7a2e15261c18daacf9, which resolves this issue. Behaviour now matches Chrome. All close buttons are visible until ```tabClipWith``` is reached. At this point they are hidden properly, except for on selected tab, where it remains visible and replaces the favicon when tab reaches minimum width (36px) and tabs overflow.
