### ISSUE TITLE
Insecure password warning - text color

### ISSUE THREAD

**Issue by MikoMagni** [muckSponge/MaterialFox#72]
I just noticed that in the latest update the "Insecure password warning" text is black on black. See screenshot

<img width="454" alt="screen shot 2019-02-12 at 1 53 37 pm" src="https://user-images.githubusercontent.com/2527231/52609595-b6891800-2e75-11e9-88ab-a1d35e0fcf7c.png">

https://support.mozilla.org/en-US/kb/insecure-password-warning-firefox

<img width="511" alt="screen shot 2019-02-12 at 2 11 26 pm" src="https://user-images.githubusercontent.com/2527231/52610286-78412800-2e78-11e9-97fd-967c2c5a34c0.png">

**Comment by muckSponge** [comment]
Tested and confirmed fixed so will close but let me know if you still have the problem and I'll reopen.
