### ISSUE TITLE
Firefox automatically minimizing after leaving fullscreen

### ISSUE THREAD

**Issue by duergrim** [muckSponge/MaterialFox#73]

**Comment by duergrim** [comment]
Firefox is automatically minimizing my window after I watch a fullscreen video on youtube and press esc to leave fullscreen.

**What OS?**
Linux Mint 19.1 XFCE

**When did this problem happen?**
When disabling the title bar in "Customize" and restarting firefox.

**What fixed the problem?**
Enabling the title bar in "Customize" and restarting firefox.

**What firefox version are you running?**

Latest version. 65.0 (64-bit).

**Comment by muckSponge** [comment]
Can you confirm that this occurs only with MaterialFox installed - not in vanilla Firefox?

To add a new entry for `materialFox.reduceTabOverflow`, go to about:config, right click, select New > Boolean > "materialFox.reduceTabOverflow" > true. It will require a restart for changes to take effect, but this probably won't impact on this issue you're experiencing.

**Comment by duergrim** [comment]
Can confirm that this is a firefox issue, nothing to do with materialfox. Sorry @muckSponge

**Comment by duergrim** [comment]
Thanks for teaching me how to add an entry, i'll close the issue now.
