### ISSUE TITLE
Tabs do not have any borders

### ISSUE THREAD

**Issue by jackprob** [muckSponge/MaterialFox#74]
Hi, thanks very much for the nice theme. I installed it but now my tabs look like this:
![image](https://user-images.githubusercontent.com/36381236/52904886-52c66c80-3232-11e9-9ea5-196a1a03ab1e.png)
I am on Linux (Manjaro Linux). Is there any way to get the right behaviour?
Also, the current tab is not highlighted.

**Comment by muckSponge** [comment]
Weird. What happens if you select the dark theme or a custom lightweight theme?

**Comment by muckSponge** [comment]
No idea if this is still an issue but some recent commits may have improved this behaviour.

**Comment by muckSponge** [comment]
I'm going to close this because I've pushed quite a few commits affecting colouring and it's likely this is no longer an issue. If you find it is still a problem let me know and I'll re-open.
