### ISSUE TITLE
DevTools menu display strangely

### ISSUE THREAD

**Issue by locness3** [muckSponge/MaterialFox#75]
The ... menu in DevTools looks like this with DevTools dark mode : 
![capture d ecran 2019-02-19 a 11 47 54](https://user-images.githubusercontent.com/37651007/53009671-50376300-343c-11e9-919a-98790fc38965.png)

**Comment by muckSponge** [comment]
I'm able to reproduce this. I think best thing to do here is just not theme the dev tools menus. I'll work on finding a more specific CSS selector to ignore dev tools menus.

**Comment by locness3** [comment]
Please fix that since when hovering images links the popup comes in front of the pointer, making it go away instantly. @muckSponge

**Comment by muckSponge** [comment]
Try the [popup-refresh](https://github.com/muckSponge/MaterialFox/tree/popup-refresh) branch. I've stripped out most of the `menu` and `menupopup` code and am rebuilding it piece by piece. Only `menupopups` are affected at the moment which means all of the dev tools menus are untouched.

The refresh is based on the [Material Menus spec](https://material.io/design/components/menus.html) and will be as OS-independent as possible.

**Comment by muckSponge** [comment]
I'll close this issue now, as popup-refresh will merge with master soon and I can verify that this is no longer an issue in that branch.
