### ISSUE TITLE
Light theme with white tabs

### ISSUE THREAD

**Issue by manuelpoelzl** [muckSponge/MaterialFox#76]
Hi there,

first of, this is an awesome firefox customization! 
I wonder if it is possible - to get white tabs and the whole above section (bookmark bar, adress bar) in white like chrome. Whenever i use the white theme - nothing changes, it stays black.

Any help would be appreciated

**Comment by muckSponge** [comment]
Thanks! Would you mind showing a screenshot? It sounds like perhaps it isn't quite set up correctly, or maybe a compatibility issue with your OS.

**Comment by manuelpoelzl** [comment]
Hi sure!
![grafik](https://user-images.githubusercontent.com/46539758/53231689-d5638780-3689-11e9-9b2b-a4c9d0a51a5a.png)

This is what i get, when i use the firefox light theme

Oh, just for info, iam on windows 10

**Comment by manuelpoelzl** [comment]
Ah i figured it out, i missed that in private mode - the dark theme is automatically used!

is there a possibility to use the light theme in private mode?

**Comment by muckSponge** [comment]
Hey, sorry I didn't get back to you on this. Currently not possible but if you look inside, I think, vars.css, and remove any line referring to `[privatebrowsing]`, it should produce the behaviour you're after.
