### ISSUE TITLE
Broken Bookmark menu

### ISSUE THREAD

**Issue by TowelBin** [muckSponge/MaterialFox#79]
![bookmark-issue](https://i.imgur.com/aldhfXY.png)

**Comment by muckSponge** [comment]
How does this look in [popup-refresh](https://github.com/muckSponge/MaterialFox/tree/popup-refresh)? I'm still testing it and needs a good round of testing on Windows but otherwise a lot of this stuff should be less buggy.

**Comment by muckSponge** [comment]
This specific issue has been fixed in popup-reftesh. Any further problems can get their own issue.
