### ISSUE TITLE
The 13th commit introduced a bug in the empty URL bar

### ISSUE THREAD

**Issue by ovasquez** [muckSponge/MaterialFox#8]
### Description
The URL bar becomes smaller when empty
Commit Id: 8171483a8e12734695463a7b5209b3d659441d01

### Steps to reproduce
You can either:
- Open a new tab (URL bar should be empty)
- Clear the contents of an active URL bar

It's easily noticed when adding/removing a single character from the URL bar

### System Details
- Windows 10
- Tested on Firefox 61 and Firefox Developer Edition 63.0b1
- Tested with different themes

**Comment by muckSponge** [comment]
Sorry I missed this one last night - didn't test on Windows and problem never appeared on macOS. Should be fine now.
