### ISSUE TITLE
linux testing

### ISSUE THREAD

**Issue by edoz90** [muckSponge/MaterialFox#82]
Hi!

I use this theme currently on 3 linux machines without issues. The README says that it's untested so I want to ask you if there are some steps to follow before saying: "it's works"!

**Comment by Eddi2015** [comment]
Well I was the guy who did the linux tests originally. Basically you just take a screenshot and say "it works". The thing is, I had some issues with this theme lately: https://github.com/muckSponge/MaterialFox/issues/83

**Comment by muckSponge** [comment]
There are many distros of Linux which makes it virtually impossible for me to test them all, and some seem to work fine while others don't play nice so I've put a note in the README to let everyone know there could be issues with Linux. That, and I typically don't test Linux unless fixing a specific issue someone has posted. If it works for you, that's great :) Feel free to comment on Linux issues to let us know it's not a problem on your distro.
