### ISSUE TITLE
1px border left of the 1st tab

### ISSUE THREAD

**Issue by koolza** [muckSponge/MaterialFox#84]
Hi,

I saw it on a few screenshot that were share here, I have a 1px left border of the tab, pinned or not :
<img width="177" alt="Capture d’écran 2019-03-16 à 17 51 43" src="https://user-images.githubusercontent.com/2745330/54478601-35c29080-4814-11e9-91ad-5c6e8badbc25.png">
Do you have a solution? Is it already a known issue?
Thanks,
Alex

**Comment by muckSponge** [comment]
This was probably resolved some time ago. I think it was due to Mozilla changing the class of their titlebar spacers. I'll close it now but comment if you notice it is still happening.
