### ISSUE TITLE
Search box shadow gets darker and darker while typing

### ISSUE THREAD

**Issue by DevPre24** [muckSponge/MaterialFox#85]
When typing the left part of the search box' shadow gets darker and darker until it becomes black. At every typed key it gets a a shade darker.

<details>
 <a href="https://imgur.com/a/quF99Ex">Imgur Album</a>
  <summary>Click to expand (Images)</summary>
  <img src="https://i.imgur.com/aBBcz7C.png">
  <img src="https://i.imgur.com/iJfRkqp.png">
</details>

OS: Arch Linux 
Firefox Version: 66.0.2-1
Material Fox version: latest (master)

**Comment by DevPre24** [comment]
Temporary Fix:
- Open the file navbar/navbar.css
- Locate the line 453 (filter: drop-shadow(0 12px 6px rgba(0, 0, 0, .25)) !important;)
- Comment it by adding two slashes before it (//filter: drop-shadow(0 12px 6px rgba(0, 0, 0, .25)) !important;)

**Comment by muckSponge** [comment]
Check out [popup-refresh](https://github.com/muckSponge/MaterialFox/tree/popup-refresh) and you should see some improvements here.

**Comment by DevPre24** [comment]
> Check out [popup-refresh](https://github.com/muckSponge/MaterialFox/tree/popup-refresh) and you should see some improvements here.
> 
> I no longer use the `drop-shadow` filter and instead use a fairly complicated array of `box-shadow`ed elements and `clip-path`s to achieve the same result.

Thanks for the update.
I confirm that with the popup-refresh branch the shadow around the popup was corrected and it's not an issue anymore.

I just noticed a small bug, there's a weird border floating around the old shape of the popup.

<details>
  <summary>Click to expand (Image)</summary>
  <img src="https://i.imgur.com/M2Bv6ef.png">
</details>

**Comment by muckSponge** [comment]
If you paste the following code somewhere in your userChrome.css file, does it remove the border? Still need to do a round of testing on Windows and Linux so this is probably a simple fix.

```css
#urlbar-results
{
	border: 0 !important;
}
```

**Comment by DevPre24** [comment]
> If you paste the following code somewhere in your userChrome.css file, does it remove the border? Still need to do a round of testing on Windows and Linux so this is probably a simple fix.
> 
> ```css
> #urlbar-results
> {
> 	border: 0 !important;
> }
> ```

Unfortunately this doesn't seem to fix the issue, the border still shows up.

**Comment by muckSponge** [comment]
Of course, my fault. You'd be on 67, so the selector would be `#PopupAutoCompleteRichResult`, not `#urlbar-results`, sorry!

**Comment by DevPre24** [comment]
> Of course, my fault. You'd be on 67, so the selector would be `#PopupAutoCompleteRichResult`, not `#urlbar-results`, sorry!

Thanks for the quick fix. The border now doesn't show up anymore as expected. Totally forgot to update the browser version in the first post, my fault.

**Comment by muckSponge** [comment]
Nah, that selector I used was for 68+, which is what I happened to be testing with at the time, so my fault, I insist! ;)

I'll close this. Expect popup-refresh to merge into master within the next few days. Thanks for testing.
