### ISSUE TITLE
Display bug on nightly (68)

### ISSUE THREAD

**Issue by aelisya** [muckSponge/MaterialFox#87]
![BUG](https://cdn.discordapp.com/attachments/534038175471894528/567801361538744366/bug.png)

the tab bug on my nightly version (68) of firefox.

**Comment by scorthyn** [comment]
yep can confirme it bugs on nightly but not normal version, would appreciate a fix :D

**Comment by muckSponge** [comment]
I'll have a look but y'all shouldn't be theming a nightly, that's asking for trouble! I'll chalk it up to you guys being proactive testers.

**Comment by muckSponge** [comment]
68 seems to ignore `-moz-image-rect` cropping when scaling `background-image`s via `background-size`, probably just for SVGs. This means if you're using `-moz-image-rect` with an SVG to replicate `-moz-border-image` behaviour like I have been, the middle part is going to be stretched when the tab is wider than that part in the SVG, but in 68 this causes it to expose the cropped portions of the SVG, thus ruining the point of using `-moz-image-rect` for cropping.

I've replaced it with `::before` and `::after` pseudo elements with no `background`, using a `box-shadow` to fill in a corner, kind of like a circle mask. Doesn't seem to break anything but I'll keep the issue open for a little while to be sure.

**Comment by scorthyn** [comment]
Its fixed :D , using latest nightly , thanks a lot

**Comment by muckSponge** [comment]
Great! Thanks for testing.
