### ISSUE TITLE
Tabs and nav bar

### ISSUE THREAD

**Issue by nov3o** [muckSponge/MaterialFox#90]
![image](https://user-images.githubusercontent.com/31302079/57063524-3b910a00-6ccc-11e9-8896-f3a25bd14d39.png)
Tabs are always black and rounded. With default and light fx theme nav bar just white. Tab's text colors are the same, so I don't know, on what tab I am at the moment

**Comment by nov3o** [comment]
Ubuntu Linux, regular Firefox 65.0

**Comment by jphms** [comment]
Did you follow step 2 of the instructions?

> [about:config] Set svg.context-properties.content.enabled to true (default is false).

**Comment by muckSponge** [comment]
This is indicative of not having `svg.context-properties.content.enabled` set to `true`, as @jphms has suggested. I'm going to go ahead and close it because of this, but if you set that pref to true, restart, and still have the issue make a comment and I can look into it.
