### ISSUE TITLE
Customize page bottom jump

### ISSUE THREAD

**Issue by nov3o** [muckSponge/MaterialFox#91]
When I hover "Normal" density, bottom somehow jumps up
![Screencastfrom0502201911_24](https://user-images.githubusercontent.com/31302079/57064110-0dacc500-6cce-11e9-9537-6668f1296b1c.gif)

**Comment by muckSponge** [comment]
No idea why this is occurring but I've worked out a hack which seems to work around the problem. It's some issue with the `#nav-bar` height being smaller than the default 38px (actually, the threshold seems to be 37px). I enforce a specific icon size, which affects the `#back-button` size and ultimately shrinks the `#nav-bar` to 36px, which is in line with Chrome. By hacking some padding and margins in the customisation page it seems to be ok with the slightly different `#nav-bar` height now.
