### ISSUE TITLE
Nightly bug? 

### ISSUE THREAD

**Issue by scorthyn** [muckSponge/MaterialFox#92]
![Screenshot_1](https://user-images.githubusercontent.com/481653/57370150-53163a00-7187-11e9-9868-3b455aec6b2a.png)

latest nightly appears like this, any way to fix :)? I know I shouldnt be using nightly with this skin but still ^^

**Comment by muckSponge** [comment]
Do you have `svg.context-properties.content.enabled` set to `true`?

**Comment by scorthyn** [comment]
> 
> 
> Do you have `svg.context-properties.content.enabled` set to `true`?

thanks a lot, it was false , fixed it by turning it on :D thanks!

**Comment by muckSponge** [comment]
No problemo!
