### ISSUE TITLE
tab loading animation or css animation change issue

### ISSUE THREAD

**Issue by GauravSahare27** [muckSponge/MaterialFox#93]
1st thanks to provide material fox, this think changed tab material design, but I don't like white colour tab loading animation or css animation, is it possible to change or set default Firefox css animation? As a novice user, I have no html coding knowledge, but I want to change this, how to change?

**Comment by muckSponge** [comment]
Comment out lines 338 to 364 in tabbar.css using `/* ... */` style comments if you'd like to revert the default tab load throbber (as Mozilla calls it). In case tabbar.css changes in the future, look for the lines that mention `.tab-throbber`. If you'd like to revert just the colour, line 347 can be changed from:
```css
fill: currentColor !important;
```
To:
```css
fill: var(--toolbarbutton-icon-fill-attention, currentColor) !important;
```
This will give you a blue coloured throbber by default.
