### ISSUE TITLE
Compatibility with Vivaldi-Fox

### ISSUE THREAD

**Issue by DaniellMesquita** [muckSponge/MaterialFox#95]
I've installed it alongside the [Vivaldi-Fox](https://addons.mozilla.org/pt-BR/firefox/addon/vivaldifox/) browser extension, and saw some visual errors.

**Comment by muckSponge** [comment]
Looks like it sometimes uses an unsuitable urlbar text colour and tab text colour (specifically for dark themes). This is probably a bug in my code which affects other lightweight themes too.

**Comment by muckSponge** [comment]
Things should look much better since fea4fba. Let me know how it goes.

**Comment by DaniellMesquita** [comment]
Please update the README.md about Linux testing.
![Screenshot from 2019-05-20 19-16-54](https://user-images.githubusercontent.com/6765277/58057822-79978600-7b34-11e9-8415-4be528206496.png)
The `show tabs from other devices` doesn`t looks like in Chrome.
Also, the `GitHub, Inc` shouldn`t be in green?
Btw, it looks good with colour extension, thanks!

**Comment by muckSponge** [comment]
The icon for synced tabs was reverted recently because Firefox 67+ has a Firefox Account button which is a better fit, so that icon has been changed instead. It will also be present by default. The "GitHub, Inc" text is no longer green, which keeps it in line with Chrome's behaviour.
