### ISSUE TITLE
A weird bug with ripple effect

### ISSUE THREAD

**Issue by RisingFireStar** [muckSponge/MaterialFox#96]
![MaDogIsGay](https://user-images.githubusercontent.com/23248936/57980881-90a57d80-7a39-11e9-8e05-7b233657a896.png)

**Comment by muckSponge** [comment]
Followed the [instructions](https://github.com/muckSponge/MaterialFox/blob/master/README.md#mandatory-instructions)?

**Comment by RisingFireStar** [comment]
> 
> 
> Followed the [instructions](https://github.com/muckSponge/MaterialFox/blob/master/README.md#mandatory-instructions)?

Oh snap, I've completely forgot about that! I'm sorry

**Comment by muckSponge** [comment]
All good, I might try to make the readme more clear in that aspect.
