### ISSUE TITLE
URL bar mouseover

### ISSUE THREAD

**Issue by Schanzation** [muckSponge/MaterialFox#97]
Hey! 

Page actions, Reader view etc is hidden away in the URL bar until you hover the mouse over. This is fine for me, but when I install this extention

https://addons.mozilla.org/en-GB/android/addon/terms-of-service-didnt-read/

This one also gets hidden until I mouseover. Is it possible to have this one always visible? tyty

**Comment by muckSponge** [comment]
Urlbar icons are now visible by default, unless they are built-in icons, in which case only the bookmark button is exempt. The menu button is pushed to the far right and the bookmark button will stay next to it. The order of the other buttons is not guaranteed.

Anyways, this should fix your problem.
